// ============================================================
// ChampIndex — Base de données des habitats
// Généré par scripts/import-habitats.mjs — 41 habitats
// ============================================================

export interface Habitat {
  id: string;
  name: string;
  vegetation: string;
  soilType: string;
  altitudeRange: string;
  regions: string[];
  mushroomsFound: string;
  plantsFound: string;
  berriesFound: string;
}

export const HABITATS: Habitat[] = [
  {
    id: 'chenaie-foret-de-chenes',
    name: 'Chênaie (forêt de chênes)',
    vegetation: 'Chênes pédonculés et sessiles',
    soilType: 'Sol argilo-calcaire à acide, litière épaisse',
    altitudeRange: '100-800m',
    regions: ['Toute France'],
    mushroomsFound: 'Cèpes de Bordeaux, girolles, trompettes de la mort, russules, amanite des Césars, langue de bœuf, polypore en touffe',
    plantsFound: 'Ail des ours, muguet (toxique), violettes, primevères',
    berriesFound: 'Mûres, noisettes, châtaignes (si chênaie-châtaigneraie)',
  },
  {
    id: 'hetraie-foret-de-hetres',
    name: 'Hêtraie (forêt de hêtres)',
    vegetation: 'Hêtres dominants',
    soilType: 'Sol calcaire à neutre, litière dense, ombre épaisse',
    altitudeRange: '300-1500m',
    regions: ['Toute France sauf Méditerranée'],
    mushroomsFound: 'Chanterelles en tube, trompettes de la mort, pied de mouton, hydne hérisson, russule charbonnière, clavaires',
    plantsFound: 'Ail des ours, aspérule odorante, oxalis',
    berriesFound: 'Faînes',
  },
  {
    id: 'chataigneraie',
    name: 'Châtaigneraie',
    vegetation: 'Châtaigniers',
    soilType: 'Sol acide, siliceux, granitique',
    altitudeRange: '200-800m',
    regions: ['Massif Central', 'Corse', 'Ardèche', 'Cévennes', 'Périgord'],
    mushroomsFound: 'Cèpes (tous), girolles, oronge, russule verdoyante, bolets',
    plantsFound: 'Châtaignier (feuilles tisane)',
    berriesFound: 'Châtaignes',
  },
  {
    id: 'chenaie-charmaie',
    name: 'Chênaie-charmaie',
    vegetation: 'Chênes + charmes',
    soilType: 'Sol argilo-calcaire, frais',
    altitudeRange: '100-600m',
    regions: ['Nord', 'Centre', 'Est'],
    mushroomsFound: 'Girolles, trompettes, morilles, russules, lactaires',
    plantsFound: 'Ail des ours, lierre terrestre, stellaire',
    berriesFound: 'Noisettes, mûres',
  },
  {
    id: 'frenaie-frenaie-erablaie',
    name: 'Frênaie / Frênaie-érablaie',
    vegetation: 'Frênes, érables',
    soilType: 'Sol frais, riche, alluvial, calcaire',
    altitudeRange: '100-800m',
    regions: ['Toute France'],
    mushroomsFound: 'Morilles (association frêne), pézizes',
    plantsFound: 'Ail des ours, berce commune, ortie',
    berriesFound: 'Noix (si noyers proches)',
  },
  {
    id: 'aulnaie-ripisylve',
    name: 'Aulnaie / Ripisylve',
    vegetation: 'Aulnes, saules, peupliers',
    soilType: 'Sol humide, bords de rivières, alluvial',
    altitudeRange: '0-600m',
    regions: ['Toute France'],
    mushroomsFound: 'Pholiotes, pleurotes, morillons, gyromitres (TOXIQUE)',
    plantsFound: 'Cresson de fontaine, menthe aquatique, reine-des-prés, ortie',
    berriesFound: 'Mûres',
  },
  {
    id: 'foret-de-bouleaux',
    name: 'Forêt de bouleaux',
    vegetation: 'Bouleaux',
    soilType: 'Sol acide, pauvre, sableux ou tourbeux',
    altitudeRange: '0-1500m',
    regions: ['Nord', 'Est', 'montagnes'],
    mushroomsFound: 'Bolets orangés, russule jaune, amanite tue-mouches (TOXIQUE), lactaires',
    plantsFound: 'Myrtilles (sous-bois), épilobe',
    berriesFound: 'Sève de bouleau (printemps)',
  },
  {
    id: 'foret-mixte-feuillus',
    name: 'Forêt mixte feuillus',
    vegetation: 'Mélange chênes, hêtres, charmes, tilleuls',
    soilType: 'Variable',
    altitudeRange: '100-1000m',
    regions: ['Toute France'],
    mushroomsFound: 'Grande diversité : cèpes, girolles, russules, lactaires, amanites, pieds de mouton',
    plantsFound: 'Ail des ours, ortie, lierre terrestre',
    berriesFound: 'Noisettes, mûres, faînes',
  },
  {
    id: 'pinede-foret-de-pins',
    name: 'Pinède (forêt de pins)',
    vegetation: 'Pins sylvestres, maritimes, noirs',
    soilType: 'Sol acide à calcaire selon pin, sableux',
    altitudeRange: '0-1800m',
    regions: ['Toute France selon espèce de pin'],
    mushroomsFound: 'Lactaire délicieux, lactaire sanguin, bolet jaune, bolet granulé, tricholome terreux, matsutake européen',
    plantsFound: 'Serpolet, thym (pinède méditerranéenne)',
    berriesFound: 'Pignons de pin (pin parasol)',
  },
  {
    id: 'pessiere-foret-d-epiceas',
    name: 'Pessière (forêt d\'épicéas)',
    vegetation: 'Épicéas',
    soilType: 'Sol acide, humide, altitude',
    altitudeRange: '800-2000m',
    regions: ['Alpes', 'Jura', 'Vosges', 'Pyrénées'],
    mushroomsFound: 'Lactaire des sapins, hygrophore de mars, gomphide glutineux, bolet élégant (sous mélèzes proches)',
    plantsFound: 'Myrtilles, airelles, oxalis, épilobe',
    berriesFound: 'Myrtilles, airelles',
  },
  {
    id: 'sapiniere',
    name: 'Sapinière',
    vegetation: 'Sapins blancs',
    soilType: 'Sol calcaire à neutre, frais, humide',
    altitudeRange: '600-1800m',
    regions: ['Alpes', 'Jura', 'Vosges', 'Pyrénées', 'Massif Central'],
    mushroomsFound: 'Chanterelles, pieds de mouton, russules, clavaires, sparassis crépu',
    plantsFound: 'Oxalis, aspérule',
    berriesFound: 'Framboises (clairières)',
  },
  {
    id: 'melezin',
    name: 'Mélézin',
    vegetation: 'Mélèzes',
    soilType: 'Sol acide, montagne, lumineux',
    altitudeRange: '1200-2200m',
    regions: ['Alpes', 'quelques stations Pyrénées'],
    mushroomsFound: 'Bolet élégant (spécifique mélèze), lactaires, russules',
    plantsFound: 'Génépi, myrtilles',
    berriesFound: 'Myrtilles, airelles',
  },
  {
    id: 'foret-mixte-resineux-feuillus',
    name: 'Forêt mixte résineux-feuillus',
    vegetation: 'Mélange pins/épicéas + chênes/hêtres',
    soilType: 'Variable',
    altitudeRange: '300-1500m',
    regions: ['Zones de transition montagne'],
    mushroomsFound: 'Très grande diversité, combine espèces des deux types',
    plantsFound: 'Variable',
    berriesFound: 'Variable',
  },
  {
    id: 'prairie-naturelle-paturage',
    name: 'Prairie naturelle / Pâturage',
    vegetation: 'Herbes, graminées',
    soilType: 'Sol riche, non amendé chimiquement',
    altitudeRange: '0-2000m',
    regions: ['Toute France'],
    mushroomsFound: 'Rosé des prés, coulemelle, coprin chevelu, marasme des Oréades, vesse-de-loup géante, mousseron de la St-Georges',
    plantsFound: 'Pissenlit, plantain, oseille, trèfle, pâquerette, achillée',
    berriesFound: 'Mûres (bordures)',
  },
  {
    id: 'pelouse-calcaire-seche',
    name: 'Pelouse calcaire sèche',
    vegetation: 'Herbes rases, orchidées',
    soilType: 'Sol calcaire, sec, drainé',
    altitudeRange: '100-800m',
    regions: ['Causses', 'Bourgogne', 'Champagne', 'Jura'],
    mushroomsFound: 'Hygrophore des prés, marasme des Oréades',
    plantsFound: 'Serpolet, origan, pimprenelle, sauge',
    berriesFound: 'Prunelles, cynorhodons (bordures)',
  },
  {
    id: 'lande-a-bruyere-ajoncs',
    name: 'Lande à bruyère / Ajoncs',
    vegetation: 'Bruyères, ajoncs, genêts',
    soilType: 'Sol acide, pauvre, siliceux',
    altitudeRange: '0-1500m',
    regions: ['Bretagne', 'Massif Central', 'montagnes'],
    mushroomsFound: 'Peu de champignons comestibles',
    plantsFound: 'Myrtilles (landes montagnardes)',
    berriesFound: 'Myrtilles, airelles, mûres',
  },
  {
    id: 'alpage-prairie-de-montagne',
    name: 'Alpage / Prairie de montagne',
    vegetation: 'Herbes alpines, graminées',
    soilType: 'Sol variable, altitude',
    altitudeRange: '1500-2500m',
    regions: ['Alpes', 'Pyrénées', 'Massif Central'],
    mushroomsFound: 'Mousseron de la St-Georges, rosés des prés d\'altitude',
    plantsFound: 'Génépi, gentiane jaune, arnica (protégé), épilobe',
    berriesFound: 'Myrtilles, airelles',
  },
  {
    id: 'clairiere-coupe-forestiere',
    name: 'Clairière / Coupe forestière',
    vegetation: 'Végétation pionnière après coupe',
    soilType: 'Sol forestier découvert',
    altitudeRange: 'Variable',
    regions: ['Toute France'],
    mushroomsFound: 'Morilles (l\'année suivant un incendie/coupe), pézizes, strophaires',
    plantsFound: 'Épilobe, ortie, framboisiers',
    berriesFound: 'Framboises, mûres',
  },
  {
    id: 'haie-champetre',
    name: 'Haie champêtre',
    vegetation: 'Aubépine, prunellier, noisetier, sureau, cornouiller',
    soilType: 'Sol variable, transition',
    altitudeRange: '0-800m',
    regions: ['Toute France (surtout bocage)'],
    mushroomsFound: 'Coulemelle, pied bleu, pleurotes (sur vieux troncs), coprin chevelu',
    plantsFound: 'Ail des ours (haies humides), lierre terrestre, alliaire, lamiers',
    berriesFound: 'Mûres, prunelles, cynorhodons, noisettes, sureau, cornouilles, aubépine',
  },
  {
    id: 'lisiere-forestiere',
    name: 'Lisière forestière',
    vegetation: 'Zone de transition forêt-ouvert',
    soilType: 'Sol enrichi, lumineux',
    altitudeRange: 'Variable',
    regions: ['Toute France'],
    mushroomsFound: 'Coulemelle, coprin chevelu, pied bleu, agarics, lépiotes',
    plantsFound: 'Ortie, lamiers, berce, alliaire',
    berriesFound: 'Mûres, framboises, noisettes',
  },
  {
    id: 'bord-de-chemin-forestier',
    name: 'Bord de chemin forestier',
    vegetation: 'Chemin + fossé + talus',
    soilType: 'Sol tassé, enrichi',
    altitudeRange: 'Variable',
    regions: ['Toute France'],
    mushroomsFound: 'Pézizes, coprins, strophaires, vesses-de-loup',
    plantsFound: 'Plantain, pissenlit, achillée, stellaire',
    berriesFound: 'Mûres, fraises des bois',
  },
  {
    id: 'verger-abandonne-vieux-verger',
    name: 'Verger abandonné / Vieux verger',
    vegetation: 'Pommiers, poiriers, cerisiers, pruniers',
    soilType: 'Sol enrichi, fruitiers',
    altitudeRange: '100-600m',
    regions: ['Toute France'],
    mushroomsFound: 'Morilles (sous frênes/pommiers), mousseron de la St-Georges',
    plantsFound: 'Ortie, pissenlit',
    berriesFound: 'Pommes, poires, cerises, prunes sauvages, mirabelles',
  },
  {
    id: 'berge-de-riviere-ruisseau',
    name: 'Berge de rivière / Ruisseau',
    vegetation: 'Aulnes, saules, frênes',
    soilType: 'Sol alluvial, humide en permanence',
    altitudeRange: '0-1000m',
    regions: ['Toute France'],
    mushroomsFound: 'Morillons, pholiotes du peuplier, pleurotes, oreilles de Judas',
    plantsFound: 'Cresson de fontaine, menthe aquatique, reine-des-prés, ortie, consoude',
    berriesFound: 'Mûres',
  },
  {
    id: 'marais-zone-humide',
    name: 'Marais / Zone humide',
    vegetation: 'Joncs, carex, saules',
    soilType: 'Sol gorgé d\'eau, tourbeux',
    altitudeRange: '0-500m',
    regions: ['Toute France'],
    mushroomsFound: 'Très peu de champignons comestibles',
    plantsFound: 'Guimauve officinale, salicorne (marais salants), menthe aquatique',
    berriesFound: 'Canneberge (tourbières)',
  },
  {
    id: 'tourbiere',
    name: 'Tourbière',
    vegetation: 'Sphaignes, bruyères',
    soilType: 'Sol très acide, gorgé d\'eau',
    altitudeRange: '300-1500m',
    regions: ['Vosges', 'Jura', 'Massif Central', 'Pyrénées'],
    mushroomsFound: 'Très peu (quelques lactaires)',
    plantsFound: 'Canneberge, airelle des marais',
    berriesFound: 'Canneberge, airelle des marais',
  },
  {
    id: 'fosse-humide',
    name: 'Fossé humide',
    vegetation: 'Végétation de fossé',
    soilType: 'Sol humide, enrichi',
    altitudeRange: '0-800m',
    regions: ['Toute France'],
    mushroomsFound: 'Peu',
    plantsFound: 'Cresson de terre, menthe, consoude, reine-des-prés',
    berriesFound: 'Mûres (bordure)',
  },
  {
    id: 'garrigue',
    name: 'Garrigue',
    vegetation: 'Chênes kermès, romarin, thym, lavande',
    soilType: 'Sol calcaire, sec, pierreux',
    altitudeRange: '0-600m',
    regions: ['Provence', 'Languedoc', 'Corse'],
    mushroomsFound: 'Lactaire sanguin (sous pins), pleurote du panicaut, truffe',
    plantsFound: 'Romarin, thym, sarriette, sauge, fenouil, asperge sauvage',
    berriesFound: 'Arbouses, figues, amandes',
  },
  {
    id: 'maquis',
    name: 'Maquis',
    vegetation: 'Arbousier, ciste, bruyère arborescente, myrte',
    soilType: 'Sol acide, siliceux',
    altitudeRange: '0-600m',
    regions: ['Corse', 'Maures', 'Esterel', 'Pyrénées-Orientales'],
    mushroomsFound: 'Oronge, lactaire sanguin, cèpe bronzé',
    plantsFound: 'Myrte (baies = condiment), asperge sauvage',
    berriesFound: 'Arbouses, mûres',
  },
  {
    id: 'chenaie-verte',
    name: 'Chênaie verte',
    vegetation: 'Chênes verts',
    soilType: 'Sol calcaire, sec',
    altitudeRange: '0-800m',
    regions: ['Midi méditerranéen'],
    mushroomsFound: 'Oronge, cèpe bronzé, truffe noire',
    plantsFound: 'Asperge sauvage, fenouil',
    berriesFound: 'Glands doux (chêne vert)',
  },
  {
    id: 'oliveraie-verger-mediterraneen',
    name: 'Oliveraie / Verger méditerranéen',
    vegetation: 'Oliviers, amandiers, figuiers',
    soilType: 'Sol calcaire, terrasses',
    altitudeRange: '0-500m',
    regions: ['Provence', 'Languedoc', 'Corse'],
    mushroomsFound: 'Pleurote du panicaut (dans les champs)',
    plantsFound: 'Fenouil, roquette sauvage, pourpier',
    berriesFound: 'Figues, amandes (cultivés mais subspontanés)',
  },
  {
    id: 'pinede-mediterraneenne',
    name: 'Pinède méditerranéenne',
    vegetation: 'Pins d\'Alep, pins maritimes',
    soilType: 'Sol calcaire à sableux, sec',
    altitudeRange: '0-600m',
    regions: ['Littoral méditerranéen'],
    mushroomsFound: 'Lactaire sanguin, lactaire délicieux, bolet granulé, truffe d\'été',
    plantsFound: 'Ciste (non comestible), romarin, thym',
    berriesFound: 'Pignons de pin',
  },
  {
    id: 'estran-rocheux',
    name: 'Estran rocheux',
    vegetation: 'Rochers, flaques',
    soilType: 'Roche avec algues',
    altitudeRange: '0m',
    regions: ['Tout littoral'],
    mushroomsFound: 'Aucun champignon',
    plantsFound: 'Algues : laitue de mer, dulse, nori, wakamé, kombu, haricot de mer, fucus',
    berriesFound: 'Aucun',
  },
  {
    id: 'pre-sale-marais-salant',
    name: 'Pré salé / Marais salant',
    vegetation: 'Végétation halophile',
    soilType: 'Sol salé, vaseux',
    altitudeRange: '0m',
    regions: ['Atlantique', 'Manche', 'Méditerranée'],
    mushroomsFound: 'Aucun champignon',
    plantsFound: 'Salicorne, obione, aster maritime, soude maritime, plantain maritime',
    berriesFound: 'Aucun',
  },
  {
    id: 'dune-littorale',
    name: 'Dune littorale',
    vegetation: 'Oyats, argousier',
    soilType: 'Sol sableux',
    altitudeRange: '0-20m',
    regions: ['Atlantique', 'Manche'],
    mushroomsFound: 'Très peu',
    plantsFound: 'Pourpier de mer',
    berriesFound: 'Argousier',
  },
  {
    id: 'falaise-littorale',
    name: 'Falaise littorale',
    vegetation: 'Végétation de falaise',
    soilType: 'Sol mince sur roche',
    altitudeRange: '0-50m',
    regions: ['Tout littoral'],
    mushroomsFound: 'Aucun champignon',
    plantsFound: 'Criste marine, fenouil marin, bette maritime',
    berriesFound: 'Aucun',
  },
  {
    id: 'jardin-potager',
    name: 'Jardin / Potager',
    vegetation: 'Culture, haies',
    soilType: 'Sol enrichi, travaillé',
    altitudeRange: '0-800m',
    regions: ['Toute France'],
    mushroomsFound: 'Coprin chevelu, rosé des prés, strophaire à anneau rugueux',
    plantsFound: 'Ortie, pissenlit, stellaire, mouron, pourpier, bourrache, cardamine hirsute',
    berriesFound: 'Mûres (clôtures)',
  },
  {
    id: 'parc-urbain-periurbain',
    name: 'Parc urbain / Périurbain',
    vegetation: 'Arbres plantés variés',
    soilType: 'Sol enrichi, tondu',
    altitudeRange: '0-500m',
    regions: ['Toute France'],
    mushroomsFound: 'Rosé des prés, coprin chevelu, agarics, coulemelle (bordures)',
    plantsFound: 'Pissenlit, plantain, pâquerette, trèfle',
    berriesFound: 'Mûres, noix (si noyers)',
  },
  {
    id: 'friche-terrain-vague',
    name: 'Friche / Terrain vague',
    vegetation: 'Végétation pionnière',
    soilType: 'Sol perturbé, enrichi',
    altitudeRange: '0-600m',
    regions: ['Toute France'],
    mushroomsFound: 'Coprins, agarics',
    plantsFound: 'Ortie, chénopode blanc, arroche, pourpier, mauve, fenouil sauvage',
    berriesFound: 'Mûres',
  },
  {
    id: 'vigne-olivette',
    name: 'Vigne / Olivette',
    vegetation: 'Vignes, oliviers',
    soilType: 'Sol travaillé, calcaire souvent',
    altitudeRange: '0-500m',
    regions: ['Régions viticoles'],
    mushroomsFound: 'Peu',
    plantsFound: 'Poireau des vignes, mâche sauvage, roquette',
    berriesFound: 'Raisin sauvage (bords)',
  },
  {
    id: 'bord-de-route-talus',
    name: 'Bord de route / Talus',
    vegetation: 'Végétation rudérale',
    soilType: 'Sol compacté, perturbé',
    altitudeRange: '0-1500m',
    regions: ['Toute France'],
    mushroomsFound: 'Coprin chevelu, marasme des Oréades (pelouse)',
    plantsFound: 'Tussilage, pissenlit, plantain, achillée, fenouil, barbarée',
    berriesFound: 'Cynorhodons, prunelles, mûres',
  },
  {
    id: 'mur-ruine',
    name: 'Mur / Ruine',
    vegetation: 'Végétation rupicole',
    soilType: 'Sol mince, pierre',
    altitudeRange: '0-800m',
    regions: ['Toute France'],
    mushroomsFound: 'Aucun champignon notable',
    plantsFound: 'Nombril de Vénus (Ouest), cardamine hirsute, roquette sauvage, câprier (extrême Sud)',
    berriesFound: 'Figues (murs ensoleillés, Sud)',
  },
];
