// ============================================================
// ChampIndex — Lieux de foraging en France
// Généré depuis foraging_lieux_complet.xlsx — 135 lieux
// ============================================================

export interface ForagingLocation {
  id: string;
  name: string;
  department: string;
  region: string;
  areaHectares?: number;
  habitatType: string;
  mainMushrooms: string;
  mainPlants: string;
  mainBerries: string;
  bestPeriod: string;
  notes: string;
  lat: number;
  lng: number;
}

export const FORAGING_LOCATIONS: ForagingLocation[] = [
  {
    id: 'foret-de-fontainebleau',
    name: 'Forêt de Fontainebleau',
    department: 'Seine-et-Marne (77)',
    region: 'Île-de-France',
    areaHectares: 25000,
    habitatType: 'Chênaie-hêtraie, pins, grès, chaos rocheux',
    mainMushrooms: 'Cèpes de Bordeaux, girolles, chanterelles, trompettes, pieds de mouton, coulemelles, russules, amanites des Césars',
    mainPlants: 'Ail des ours, muguet (attention toxique), violettes, primevères, lierre terrestre',
    mainBerries: 'Châtaignes, mûres, noisettes, fraises des bois, cynorhodons',
    bestPeriod: 'Sep-Nov (champignons), Mar-Avr (plantes)',
    notes: 'Forêt domaniale, accès libre. Zones de réserve biologique intégrale interdites. Très fréquentée le week-end.',
    lat: 48.4,
    lng: 2.7,
  },
  {
    id: 'foret-de-rambouillet',
    name: 'Forêt de Rambouillet',
    department: 'Yvelines (78)',
    region: 'Île-de-France',
    areaHectares: 22000,
    habitatType: 'Chênaie, hêtraie, zones humides, étangs',
    mainMushrooms: 'Cèpes, girolles, trompettes de la mort, pieds de mouton, morilles (rares, vallées)',
    mainPlants: 'Ail des ours, ortie, stellaire, lierre terrestre, lamiers',
    mainBerries: 'Mûres, noisettes, châtaignes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Domaniale, accès libre. Cueillette limitée à 5 kg/personne/jour.',
    lat: 48.6,
    lng: 1.8,
  },
  {
    id: 'foret-de-saint-germain-en-laye',
    name: 'Forêt de Saint-Germain-en-Laye',
    department: 'Yvelines (78)',
    region: 'Île-de-France',
    areaHectares: 3500,
    habitatType: 'Chênaie-charmaie, zones humides',
    mainMushrooms: 'Girolles, trompettes, pieds bleus, russules, coulemelles',
    mainPlants: 'Ail des ours (secteur humide), ortie, plantain',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Proche Paris, RER A. Très accessible mais aussi très cueillie.',
    lat: 48.9,
    lng: 2.1,
  },
  {
    id: 'foret-de-senart',
    name: 'Forêt de Sénart',
    department: 'Essonne (91)',
    region: 'Île-de-France',
    areaHectares: 3200,
    habitatType: 'Chênaie, châtaigneraie, zones humides',
    mainMushrooms: 'Girolles, trompettes, chanterelles en tube, cèpes (rares), russules',
    mainPlants: 'Ail des ours (Mare aux Évées), ortie, pissenlit',
    mainBerries: 'Mûres, châtaignes, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'RER D accessible. Forêt domaniale.',
    lat: 48.65,
    lng: 2.48,
  },
  {
    id: 'foret-de-montmorency',
    name: 'Forêt de Montmorency',
    department: 'Val-d\'Oise (95)',
    region: 'Île-de-France',
    areaHectares: 2200,
    habitatType: 'Châtaigneraie dominante',
    mainMushrooms: 'Cèpes, girolles, coulemelles, russules, bolets bai',
    mainPlants: 'Ortie, lierre terrestre, alliaire',
    mainBerries: 'Châtaignes +++ (plus grande châtaigneraie d\'IDF), mûres, noisettes',
    bestPeriod: 'Oct-Nov',
    notes: 'Plus grande châtaigneraie d\'IDF. Très fréquentée en automne.',
    lat: 49.02,
    lng: 2.32,
  },
  {
    id: 'foret-de-meudon',
    name: 'Forêt de Meudon',
    department: 'Hauts-de-Seine (92)',
    region: 'Île-de-France',
    areaHectares: 1100,
    habitatType: 'Chênaie-châtaigneraie',
    mainMushrooms: 'Girolles, trompettes, pieds bleus, coulemelles',
    mainPlants: 'Ail des ours, ortie, lamiers',
    mainBerries: 'Châtaignes, mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Très proche Paris. Petite mais productive.',
    lat: 48.79,
    lng: 2.23,
  },
  {
    id: 'foret-de-compiegne',
    name: 'Forêt de Compiègne',
    department: 'Oise (60)',
    region: 'Hauts-de-France',
    areaHectares: 14400,
    habitatType: 'Hêtraie-chênaie, plaine, vallée de l\'Aisne',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, morilles (bords d\'Aisne), pieds de mouton, chanterelles',
    mainPlants: 'Ail des ours +++, ortie, berce commune, reine-des-prés',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov (champignons), Mar-Avr (ail des ours)',
    notes: '3ème plus grande forêt domaniale de France. Carrefours historiques.',
    lat: 49.37,
    lng: 2.92,
  },
  {
    id: 'foret-d-halatte',
    name: 'Forêt d\'Halatte',
    department: 'Oise (60)',
    region: 'Hauts-de-France',
    areaHectares: 4300,
    habitatType: 'Chênaie-hêtraie, sols variés',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton',
    mainPlants: 'Ail des ours, muguet (toxique), violettes',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Domaniale. Moins fréquentée que Compiègne.',
    lat: 49.22,
    lng: 2.63,
  },
  {
    id: 'foret-de-crecy-en-brie',
    name: 'Forêt de Crécy-en-Brie',
    department: 'Seine-et-Marne (77)',
    region: 'Île-de-France',
    areaHectares: 3000,
    habitatType: 'Chênaie sur argile à meulière',
    mainMushrooms: 'Cèpes, girolles, pieds de mouton, russules',
    mainPlants: 'Ortie, plantain, stellaire',
    mainBerries: 'Mûres, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Sols argileux lourds, bons après pluie.',
    lat: 48.85,
    lng: 2.9,
  },
  {
    id: 'foret-d-ermenonville',
    name: 'Forêt d\'Ermenonville',
    department: 'Oise (60)',
    region: 'Hauts-de-France',
    areaHectares: 3300,
    habitatType: 'Pinède, chênaie sur sable, landes',
    mainMushrooms: 'Bolets jaunes, lactaires, russules, coulemelles',
    mainPlants: 'Bruyère (non comestible), pissenlit, plantain',
    mainBerries: 'Mûres, myrtilles (très localisées)',
    bestPeriod: 'Sep-Nov',
    notes: 'Mer de sable à côté. Sols sableux, acides.',
    lat: 49.13,
    lng: 2.62,
  },
  {
    id: 'foret-de-villefermoy',
    name: 'Forêt de Villefermoy',
    department: 'Seine-et-Marne (77)',
    region: 'Île-de-France',
    areaHectares: 2800,
    habitatType: 'Chênaie sur argile',
    mainMushrooms: 'Cèpes, girolles, trompettes',
    mainPlants: 'Ail des ours, ortie',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Moins connue, moins cueillie. Bon potentiel.',
    lat: 48.45,
    lng: 2.85,
  },
  {
    id: 'bois-de-vincennes',
    name: 'Bois de Vincennes',
    department: 'Paris (75)',
    region: 'Île-de-France',
    areaHectares: 995,
    habitatType: 'Parc urbain boisé',
    mainMushrooms: 'Coprins chevelu, rosés des prés (pelouses), agarics',
    mainPlants: 'Pissenlit, plantain, pâquerette, trèfle',
    mainBerries: 'Mûres (rares)',
    bestPeriod: 'Sep-Oct',
    notes: 'Urbain. Qualité des sols incertaine, éviter bords de routes.',
    lat: 48.83,
    lng: 2.43,
  },
  {
    id: 'foret-de-ferrieres',
    name: 'Forêt de Ferrières',
    department: 'Seine-et-Marne (77)',
    region: 'Île-de-France',
    areaHectares: 2800,
    habitatType: 'Chênaie-charmaie',
    mainMushrooms: 'Girolles, trompettes, pieds de mouton, russules',
    mainPlants: 'Ail des ours, lierre terrestre',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Privée en partie (Rothschild). Vérifier accès.',
    lat: 48.82,
    lng: 2.72,
  },
  {
    id: 'foret-de-brotonne',
    name: 'Forêt de Brotonne',
    department: 'Seine-Maritime (76)',
    region: 'Normandie',
    areaHectares: 7200,
    habitatType: 'Hêtraie-chênaie, vallée de Seine',
    mainMushrooms: 'Cèpes, girolles, trompettes, chanterelles en tube, pieds de mouton, pleurotes',
    mainPlants: 'Ail des ours, berce commune, ortie, reine-des-prés',
    mainBerries: 'Mûres, noisettes, pommes sauvages, poires sauvages',
    bestPeriod: 'Sep-Nov',
    notes: 'Parc naturel régional des Boucles de la Seine normande.',
    lat: 49.45,
    lng: 0.72,
  },
  {
    id: 'foret-d-ecouves',
    name: 'Forêt d\'Écouves',
    department: 'Orne (61)',
    region: 'Normandie',
    areaHectares: 8000,
    habitatType: 'Hêtraie-chênaie, point culminant de Normandie (417m)',
    mainMushrooms: 'Cèpes, girolles, trompettes, chanterelles en tube, pieds bleus, bolets bai',
    mainPlants: 'Ail des ours, aspérule odorante, oxalis',
    mainBerries: 'Myrtilles (rares, crêtes), mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus grande forêt de Normandie. Altitude favorable.',
    lat: 48.48,
    lng: 0.08,
  },
  {
    id: 'foret-d-eu',
    name: 'Forêt d\'Eu',
    department: 'Seine-Maritime (76)',
    region: 'Normandie',
    areaHectares: 9300,
    habitatType: 'Hêtraie sur craie, vallée de la Bresle',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton, morilles (vallée)',
    mainPlants: 'Ail des ours +++, aspérule, muguet',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Très grande forêt, peu fréquentée.',
    lat: 49.98,
    lng: 1.53,
  },
  {
    id: 'foret-de-lyons',
    name: 'Forêt de Lyons',
    department: 'Eure (27)',
    region: 'Normandie',
    areaHectares: 10700,
    habitatType: 'Hêtraie cathédrale, l\'une des plus belles de France',
    mainMushrooms: 'Cèpes, girolles, trompettes +++, pieds de mouton, chanterelles',
    mainPlants: 'Ail des ours, aspérule odorante, violettes',
    mainBerries: 'Mûres, noisettes, faînes',
    bestPeriod: 'Sep-Nov',
    notes: 'Hêtraie majestueuse. Sols argilo-calcaires excellents.',
    lat: 49.4,
    lng: 1.55,
  },
  {
    id: 'foret-d-eawy',
    name: 'Forêt d\'Eawy',
    department: 'Seine-Maritime (76)',
    region: 'Normandie',
    areaHectares: 6600,
    habitatType: 'Hêtraie pure',
    mainMushrooms: 'Trompettes +++, chanterelles en tube, pieds de mouton, russules',
    mainPlants: 'Aspérule odorante, oxalis, ail des ours',
    mainBerries: 'Faînes, mûres',
    bestPeriod: 'Oct-Nov',
    notes: 'Allée des Limousins (hêtres remarquables).',
    lat: 49.72,
    lng: 1.28,
  },
  {
    id: 'foret-de-cerisy',
    name: 'Forêt de Cerisy',
    department: 'Calvados / Manche',
    region: 'Normandie',
    areaHectares: 2100,
    habitatType: 'Hêtraie-chênaie ancienne',
    mainMushrooms: 'Girolles, trompettes, pieds de mouton, clavaires',
    mainPlants: 'Ail des ours, aspérule, violettes',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Réserve naturelle. Zones protégées à respecter.',
    lat: 49.18,
    lng: -0.87,
  },
  {
    id: 'foret-de-belleme',
    name: 'Forêt de Bellême',
    department: 'Orne (61)',
    region: 'Normandie',
    areaHectares: 2400,
    habitatType: 'Chênaie sessiliflore, hêtraie',
    mainMushrooms: 'Cèpes, girolles, trompettes, russules charbonnières',
    mainPlants: 'Ail des ours, muguet, ortie',
    mainBerries: 'Mûres, noisettes, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Forêt de chênes réputée pour les cèpes.',
    lat: 48.37,
    lng: 0.57,
  },
  {
    id: 'foret-du-perche-reno-valdieu',
    name: 'Forêt du Perche (Réno-Valdieu)',
    department: 'Orne (61)',
    region: 'Normandie',
    areaHectares: 3200,
    habitatType: 'Chênaie-hêtraie, bocage percheron',
    mainMushrooms: 'Cèpes, girolles, pieds de mouton, coulemelles',
    mainPlants: 'Ail des ours, primevères, violettes',
    mainBerries: 'Pommes sauvages, poires sauvages, mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Perche = vergers abandonnés = pommes/poires sauvages.',
    lat: 48.42,
    lng: 0.68,
  },
  {
    id: 'cote-de-nacre-cote-fleurie-estran',
    name: 'Côte de Nacre / Côte Fleurie (estran)',
    department: 'Calvados (14)',
    region: 'Normandie',
    habitatType: 'Estran rocheux, platiers',
    mainMushrooms: 'Aucun',
    mainPlants: 'Algues : laitue de mer, fucus, dulse (rare)',
    mainBerries: 'Aucun',
    bestPeriod: 'Avr-Sep (algues)',
    notes: 'Estran accessible à marée basse. Vérifier qualité eaux.',
    lat: 49.3,
    lng: -0.4,
  },
  {
    id: 'baie-du-mont-saint-michel-pres-sales',
    name: 'Baie du Mont-Saint-Michel (prés salés)',
    department: 'Manche (50)',
    region: 'Normandie',
    habitatType: 'Prés salés, herbus',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne +++, obione, aster maritime, soude maritime',
    mainBerries: 'Aucun',
    bestPeriod: 'Jun-Sep (salicorne)',
    notes: 'Zone protégée. Cueillette de salicorne tolérée en quantité raisonnable. Attention marées !',
    lat: 48.63,
    lng: -1.52,
  },
  {
    id: 'foret-de-grimbosq',
    name: 'Forêt de Grimbosq',
    department: 'Calvados (14)',
    region: 'Normandie',
    areaHectares: 1100,
    habitatType: 'Résineux et feuillus mélangés',
    mainMushrooms: 'Girolles, lactaires, bolets, russules',
    mainPlants: 'Ortie, stellaire, digitale (toxique)',
    mainBerries: 'Mûres, framboises',
    bestPeriod: 'Sep-Nov',
    notes: 'Base de loisirs, bien balisée.',
    lat: 48.97,
    lng: -0.45,
  },
  {
    id: 'foret-de-paimpont-broceliande',
    name: 'Forêt de Paimpont (Brocéliande)',
    department: 'Ille-et-Vilaine (35)',
    region: 'Bretagne',
    areaHectares: 9000,
    habitatType: 'Chênaie, hêtraie, landes, étangs',
    mainMushrooms: 'Cèpes, girolles, bolets bai, pieds de mouton, coulemelles, pleurotes',
    mainPlants: 'Ail des ours, ortie, fougère (non comestible), digitale (toxique)',
    mainBerries: 'Mûres, châtaignes, myrtilles (landes), noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Forêt mythique de Brocéliande. Humidité bretonne favorable aux champignons.',
    lat: 48,
    lng: -2.17,
  },
  {
    id: 'foret-de-huelgoat',
    name: 'Forêt de Huelgoat',
    department: 'Finistère (29)',
    region: 'Bretagne',
    areaHectares: 1000,
    habitatType: 'Chênaie-hêtraie, chaos granitique',
    mainMushrooms: 'Cèpes, girolles, chanterelles, bolets bai, pieds de mouton',
    mainPlants: 'Ail des ours, fougères, mousses, ortie',
    mainBerries: 'Mûres, myrtilles, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Chaos rocheux spectaculaire. Microclimats humides.',
    lat: 48.37,
    lng: -3.75,
  },
  {
    id: 'foret-du-cranou',
    name: 'Forêt du Cranou',
    department: 'Finistère (29)',
    region: 'Bretagne',
    areaHectares: 610,
    habitatType: 'Chênaie-hêtraie',
    mainMushrooms: 'Girolles, chanterelles en tube, pieds de mouton',
    mainPlants: 'Ail des ours, aspérule',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Petite mais riche. Sol acide.',
    lat: 48.3,
    lng: -4.08,
  },
  {
    id: 'foret-de-quenecan',
    name: 'Forêt de Quénécan',
    department: 'Morbihan (56)',
    region: 'Bretagne',
    areaHectares: 4000,
    habitatType: 'Hêtraie-chênaie, lac de Guerlédan',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton, bolets orangés',
    mainPlants: 'Ail des ours, ortie, reine-des-prés',
    mainBerries: 'Mûres, myrtilles (landes), châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Lac de Guerlédan à proximité. Forêt profonde et humide.',
    lat: 48.2,
    lng: -3.05,
  },
  {
    id: 'foret-de-coat-an-noz-coat-an-hay',
    name: 'Forêt de Coat-an-Noz / Coat-an-Hay',
    department: 'Côtes-d\'Armor (22)',
    region: 'Bretagne',
    areaHectares: 1200,
    habitatType: 'Hêtraie',
    mainMushrooms: 'Girolles, chanterelles en tube, trompettes, pieds de mouton',
    mainPlants: 'Ail des ours, aspérule, oxalis',
    mainBerries: 'Mûres, faînes',
    bestPeriod: 'Oct-Nov',
    notes: 'Deux forêts jumelles, très humides.',
    lat: 48.52,
    lng: -3.4,
  },
  {
    id: 'landes-de-lanvaux',
    name: 'Landes de Lanvaux',
    department: 'Morbihan (56)',
    region: 'Bretagne',
    habitatType: 'Landes, chênaie dégradée',
    mainMushrooms: 'Peu de champignons comestibles',
    mainPlants: 'Bruyère, ajoncs (non comestible), ortie',
    mainBerries: 'Mûres +++, myrtilles (localisées)',
    bestPeriod: 'Jul-Sep (mûres)',
    notes: 'Landes à mûres principalement.',
    lat: 47.78,
    lng: -2.65,
  },
  {
    id: 'cotes-d-armor-finistere-estran-nord',
    name: 'Côtes d\'Armor / Finistère (estran nord)',
    department: 'Bretagne Nord',
    region: 'Bretagne',
    habitatType: 'Estran rocheux, platiers, goémon',
    mainMushrooms: 'Aucun',
    mainPlants: 'Algues : dulse +++, laitue de mer +++, nori, haricot de mer, fucus',
    mainBerries: 'Aucun',
    bestPeriod: 'Mar-Jun (pic), toute l\'année',
    notes: 'Première région de France pour les algues. Coefficient marée > 90 idéal. Roscoff = capitale.',
    lat: 48.6,
    lng: -3,
  },
  {
    id: 'golfe-du-morbihan-pres-sales',
    name: 'Golfe du Morbihan (prés salés)',
    department: 'Morbihan (56)',
    region: 'Bretagne',
    habitatType: 'Prés salés, vasières, îles',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne +++, obione, aster maritime, soude',
    mainBerries: 'Aucun',
    bestPeriod: 'Jun-Sep',
    notes: 'Réglementation locale. Quantités limitées. Accès en bateau pour certaines îles.',
    lat: 47.58,
    lng: -2.78,
  },
  {
    id: 'presqu-ile-de-crozon-estran',
    name: 'Presqu\'île de Crozon (estran)',
    department: 'Finistère (29)',
    region: 'Bretagne',
    habitatType: 'Estran rocheux, falaises',
    mainMushrooms: 'Aucun',
    mainPlants: 'Algues : dulse, laitue de mer, nori, kombu, haricot de mer',
    mainBerries: 'Criste marine (falaises)',
    bestPeriod: 'Mar-Jun',
    notes: 'Côte sauvage, très riche en algues. Accès parfois difficile.',
    lat: 48.25,
    lng: -4.5,
  },
  {
    id: 'foret-de-fougeres',
    name: 'Forêt de Fougères',
    department: 'Ille-et-Vilaine (35)',
    region: 'Bretagne',
    areaHectares: 1650,
    habitatType: 'Hêtraie-chênaie',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton',
    mainPlants: 'Ail des ours, ortie, muguet',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Belle forêt domaniale, portes de Bretagne.',
    lat: 48.38,
    lng: -1.2,
  },
  {
    id: 'foret-de-loudeac',
    name: 'Forêt de Loudéac',
    department: 'Côtes-d\'Armor (22)',
    region: 'Bretagne',
    areaHectares: 2500,
    habitatType: 'Chênaie-hêtraie',
    mainMushrooms: 'Cèpes, girolles, bolets bai',
    mainPlants: 'Ortie, ail des ours (localisé)',
    mainBerries: 'Mûres, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Centre Bretagne, moins connue.',
    lat: 48.18,
    lng: -2.75,
  },
  {
    id: 'foret-de-mervent-vouvant',
    name: 'Forêt de Mervent-Vouvant',
    department: 'Vendée (85)',
    region: 'Pays de la Loire',
    areaHectares: 5000,
    habitatType: 'Chênaie-hêtraie, vallée de la Mère',
    mainMushrooms: 'Cèpes, girolles, trompettes, coulemelles, pieds de mouton',
    mainPlants: 'Ail des ours, ortie, reine-des-prés',
    mainBerries: 'Mûres, châtaignes, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Principal massif forestier vendéen.',
    lat: 46.48,
    lng: -0.72,
  },
  {
    id: 'foret-de-berce',
    name: 'Forêt de Bercé',
    department: 'Sarthe (72)',
    region: 'Pays de la Loire',
    areaHectares: 5400,
    habitatType: 'Chênaie sessiliflore futaie cathédrale',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, pieds de mouton, russules',
    mainPlants: 'Ail des ours, muguet, violettes',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Une des plus belles futaies de chênes de France. Réputée pour les cèpes.',
    lat: 47.82,
    lng: 0.42,
  },
  {
    id: 'foret-de-chandelais',
    name: 'Forêt de Chandelais',
    department: 'Maine-et-Loire (49)',
    region: 'Pays de la Loire',
    areaHectares: 800,
    habitatType: 'Chênaie-hêtraie',
    mainMushrooms: 'Girolles, trompettes, pieds de mouton',
    mainPlants: 'Ail des ours, ortie',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Petite mais dense.',
    lat: 47.35,
    lng: -0.12,
  },
  {
    id: 'marais-poitevin',
    name: 'Marais poitevin',
    department: 'Vendée / Deux-Sèvres',
    region: 'Pays de la Loire',
    areaHectares: 100000,
    habitatType: 'Marais, canaux, frênaie têtard',
    mainMushrooms: 'Morilles +++ (sous frênes têtards !), pleurotes, pholiotes',
    mainPlants: 'Angélique (spécialité locale), ortie, menthe aquatique, reine-des-prés',
    mainBerries: 'Mûres, prunelles',
    bestPeriod: 'Avr-Mai (morilles), Jun-Sep (plantes)',
    notes: 'Frênes têtards = morilles. Zone humide exceptionnelle. \'Venise verte\'.',
    lat: 46.3,
    lng: -0.7,
  },
  {
    id: 'ile-de-noirmoutier',
    name: 'Île de Noirmoutier',
    department: 'Vendée (85)',
    region: 'Pays de la Loire',
    habitatType: 'Marais salants, estran, dunes',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne +++, obione, criste marine, algues',
    mainBerries: 'Argousier (dunes)',
    bestPeriod: 'Jun-Sep (salicorne)',
    notes: 'Récolte de salicorne traditionnelle. Marais salants.',
    lat: 47,
    lng: -2.25,
  },
  {
    id: 'foret-de-brissac-beaulieu',
    name: 'Forêt de Brissac / Beaulieu',
    department: 'Maine-et-Loire (49)',
    region: 'Pays de la Loire',
    areaHectares: 1500,
    habitatType: 'Chênaie, pinède sur sable',
    mainMushrooms: 'Cèpes, bolets, lactaires',
    mainPlants: 'Ortie, pissenlit, plantain',
    mainBerries: 'Mûres, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Sols sableux, bon pour bolets.',
    lat: 47.35,
    lng: -0.52,
  },
  {
    id: 'foret-du-gavre',
    name: 'Forêt du Gâvre',
    department: 'Loire-Atlantique (44)',
    region: 'Pays de la Loire',
    areaHectares: 4500,
    habitatType: 'Chênaie-hêtraie',
    mainMushrooms: 'Cèpes, girolles, pieds de mouton, trompettes',
    mainPlants: 'Ail des ours, ortie, muguet',
    mainBerries: 'Mûres, noisettes, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus grande forêt domaniale de Loire-Atlantique.',
    lat: 47.52,
    lng: -1.82,
  },
  {
    id: 'foret-de-saint-amand',
    name: 'Forêt de Saint-Amand',
    department: 'Nord (59)',
    region: 'Hauts-de-France',
    areaHectares: 4700,
    habitatType: 'Chênaie humide, marais, tourbière',
    mainMushrooms: 'Girolles, trompettes, chanterelles, pleurotes, russules',
    mainPlants: 'Ail des ours, reine-des-prés, menthe aquatique, ortie',
    mainBerries: 'Mûres, noisettes, prunelles',
    bestPeriod: 'Sep-Nov',
    notes: 'Zone humide diversifiée. Amandinois.',
    lat: 50.47,
    lng: 3.42,
  },
  {
    id: 'foret-de-crecy',
    name: 'Forêt de Crécy',
    department: 'Somme (80)',
    region: 'Hauts-de-France',
    areaHectares: 4300,
    habitatType: 'Hêtraie-chênaie sur craie',
    mainMushrooms: 'Cèpes, girolles, trompettes, russules, pieds de mouton',
    mainPlants: 'Ail des ours, ortie, stellaire',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Sols craie + argile à silex.',
    lat: 50.22,
    lng: 1.88,
  },
  {
    id: 'foret-de-mormal',
    name: 'Forêt de Mormal',
    department: 'Nord (59)',
    region: 'Hauts-de-France',
    areaHectares: 9163,
    habitatType: 'Chênaie-hêtraie',
    mainMushrooms: 'Cèpes, girolles, trompettes, chanterelles en tube, pieds bleus',
    mainPlants: 'Ail des ours, ortie, muguet',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus grande forêt du Nord. Ancienne forêt royale.',
    lat: 50.18,
    lng: 3.72,
  },
  {
    id: 'foret-de-retz',
    name: 'Forêt de Retz',
    department: 'Aisne (02)',
    region: 'Hauts-de-France',
    areaHectares: 13000,
    habitatType: 'Hêtraie-chênaie',
    mainMushrooms: 'Cèpes, girolles, trompettes, morilles (vallées), pieds de mouton',
    mainPlants: 'Ail des ours +++, ortie, muguet +++',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov (champignons), Mar-Avr (ail des ours)',
    notes: 'Immense forêt domaniale. Vallée de l\'Automne.',
    lat: 49.28,
    lng: 3.1,
  },
  {
    id: 'baie-de-somme',
    name: 'Baie de Somme',
    department: 'Somme (80)',
    region: 'Hauts-de-France',
    areaHectares: 7200,
    habitatType: 'Prés salés, dunes, estran',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne +++, aster maritime, obione, soude maritime',
    mainBerries: 'Argousier (dunes)',
    bestPeriod: 'Jun-Sep',
    notes: 'Réserve naturelle. Réglementation stricte. Phoques.',
    lat: 50.22,
    lng: 1.6,
  },
  {
    id: 'foret-de-laigue',
    name: 'Forêt de Laigue',
    department: 'Oise (60)',
    region: 'Hauts-de-France',
    areaHectares: 3800,
    habitatType: 'Hêtraie-chênaie, vallée de l\'Aisne',
    mainMushrooms: 'Cèpes, morilles (bords d\'Aisne), girolles, trompettes',
    mainPlants: 'Ail des ours, berce, reine-des-prés',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov (champignons), Avr-Mai (morilles)',
    notes: 'Contiguë à Compiègne, moins fréquentée.',
    lat: 49.42,
    lng: 3.02,
  },
  {
    id: 'foret-de-thierache',
    name: 'Forêt de Thiérache',
    department: 'Aisne (02)',
    region: 'Hauts-de-France',
    habitatType: 'Chênaie-hêtraie, bocage',
    mainMushrooms: 'Cèpes, girolles, pieds de mouton, trompettes',
    mainPlants: 'Ortie, ail des ours, berce',
    mainBerries: 'Mûres, pommes sauvages, poires sauvages, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Bocage préservé. Vergers hautes tiges = pommes/poires sauvages.',
    lat: 49.88,
    lng: 3.85,
  },
  {
    id: 'foret-de-haguenau',
    name: 'Forêt de Haguenau',
    department: 'Bas-Rhin (67)',
    region: 'Grand Est',
    areaHectares: 21000,
    habitatType: 'Chênaie-pinède sur sable',
    mainMushrooms: 'Cèpes +++, girolles, bolets bai, chanterelles, morilles (rares), lactaires',
    mainPlants: 'Ail des ours, muguet, ortie, asperge sauvage (rare)',
    mainBerries: 'Mûres, myrtilles, framboises, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus grande forêt de plaine d\'Alsace. Sols sableux.',
    lat: 48.82,
    lng: 7.78,
  },
  {
    id: 'massif-des-vosges-versant-alsacien',
    name: 'Massif des Vosges (versant alsacien)',
    department: 'Haut-Rhin / Bas-Rhin',
    region: 'Grand Est',
    habitatType: 'Hêtraie-sapinière, chaumes, tourbières',
    mainMushrooms: 'Cèpes, girolles, chanterelles en tube, trompettes, pieds de mouton, bolets orangés',
    mainPlants: 'Myrtilles (sous-bois), épilobe, oxalis, gentiane jaune (protégée)',
    mainBerries: 'Myrtilles +++ (chaumes), airelles, framboises, canneberge (tourbières)',
    bestPeriod: 'Jul-Août (myrtilles), Sep-Nov (champignons)',
    notes: 'Chaumes du Markstein, Grand Ballon, Gazon du Faing. Myrtilles abondantes.',
    lat: 48,
    lng: 7,
  },
  {
    id: 'foret-de-darney',
    name: 'Forêt de Darney',
    department: 'Vosges (88)',
    region: 'Grand Est',
    areaHectares: 15000,
    habitatType: 'Hêtraie-chênaie',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton, chanterelles',
    mainPlants: 'Ail des ours, muguet, ortie',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Grande forêt vosgienne de plaine.',
    lat: 48.08,
    lng: 6.05,
  },
  {
    id: 'foret-d-orient',
    name: 'Forêt d\'Orient',
    department: 'Aube (10)',
    region: 'Grand Est',
    areaHectares: 10000,
    habitatType: 'Chênaie humide, lacs',
    mainMushrooms: 'Girolles, trompettes, pieds bleus, pleurotes, morilles (bords de lacs)',
    mainPlants: 'Ail des ours, reine-des-prés, menthe aquatique',
    mainBerries: 'Mûres, prunelles, cynorhodons',
    bestPeriod: 'Sep-Nov',
    notes: 'Parc naturel régional. Lacs-réservoirs. Zones humides.',
    lat: 48.27,
    lng: 4.35,
  },
  {
    id: 'plateau-de-langres',
    name: 'Plateau de Langres',
    department: 'Haute-Marne (52)',
    region: 'Grand Est',
    habitatType: 'Hêtraie calcaire',
    mainMushrooms: 'Morilles +++ (sols calcaires), trompettes, pieds de mouton, russules',
    mainPlants: 'Ail des ours, primevères, orchidées',
    mainBerries: 'Prunelles, cynorhodons, noisettes',
    bestPeriod: 'Avr-Mai (morilles), Sep-Nov',
    notes: 'Excellent terrain à morilles. Sols calcaires + frênes.',
    lat: 47.85,
    lng: 5.33,
  },
  {
    id: 'vallee-de-la-meuse',
    name: 'Vallée de la Meuse',
    department: 'Meuse (55)',
    region: 'Grand Est',
    habitatType: 'Frênaie, peupleraie, ripisylve',
    mainMushrooms: 'Morilles +++ (sous frênes), morillons, pholiotes du peuplier',
    mainPlants: 'Ail des ours, raifort sauvage, cresson, ortie, berce',
    mainBerries: 'Mûres, prunelles, sureau noir',
    bestPeriod: 'Avr-Mai (morilles)',
    notes: 'Morilles le long des rivières sous frênes. Tradition lorraine.',
    lat: 49.1,
    lng: 5.38,
  },
  {
    id: 'foret-de-verdun-argonne',
    name: 'Forêt de Verdun / Argonne',
    department: 'Meuse / Marne',
    region: 'Grand Est',
    habitatType: 'Hêtraie-chênaie, anciennes zones de combat',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton',
    mainPlants: 'Ail des ours, ortie, stellaire',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Forêts de mémoire. Anciennes tranchées = microreliefs favorables.',
    lat: 49.18,
    lng: 5.2,
  },
  {
    id: 'foret-de-la-joux-jura',
    name: 'Forêt de la Joux (Jura)',
    department: 'Jura (39)',
    region: 'Bourgogne-FC',
    areaHectares: 2650,
    habitatType: 'Sapinière, épicéas géants',
    mainMushrooms: 'Chanterelles en tube +++, girolles, pieds de mouton, bolets élégants',
    mainPlants: 'Oxalis, myrtilles, gentiane',
    mainBerries: 'Myrtilles, framboises, airelles',
    bestPeriod: 'Jul-Nov',
    notes: 'Sapins géants (Sapin Président). Altitude 700-1000m.',
    lat: 46.75,
    lng: 6.08,
  },
  {
    id: 'foret-de-chaux',
    name: 'Forêt de Chaux',
    department: 'Jura (39)',
    region: 'Bourgogne-FC',
    areaHectares: 20500,
    habitatType: 'Chênaie-hêtraie de plaine',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton, morilles (lisières)',
    mainPlants: 'Ail des ours, muguet, ortie',
    mainBerries: 'Mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: '2ème plus grande forêt feuillue de France.',
    lat: 47.05,
    lng: 5.72,
  },
  {
    id: 'hautes-chaumes-des-vosges',
    name: 'Hautes-Chaumes des Vosges',
    department: 'Vosges / Haut-Rhin',
    region: 'Grand Est',
    habitatType: 'Chaumes (pelouses sommitales)',
    mainMushrooms: 'Rosés des prés d\'altitude, marasmes',
    mainPlants: 'Gentiane jaune (protégée), arnica (protégée), épilobe',
    mainBerries: 'Myrtilles +++, airelles rouges',
    bestPeriod: 'Jul-Août',
    notes: 'Route des Crêtes. Cueillette myrtilles réglementée localement.',
    lat: 48.02,
    lng: 7.05,
  },
  {
    id: 'foret-de-parroy',
    name: 'Forêt de Parroy',
    department: 'Meurthe-et-Moselle (54)',
    region: 'Grand Est',
    areaHectares: 5500,
    habitatType: 'Chênaie-charmaie humide',
    mainMushrooms: 'Girolles, trompettes, pieds de mouton, pleurotes',
    mainPlants: 'Ail des ours, reine-des-prés',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Forêt humide du Lunévillois.',
    lat: 48.62,
    lng: 6.55,
  },
  {
    id: 'foret-du-morvan',
    name: 'Forêt du Morvan',
    department: 'Nièvre / Saône-et-Loire',
    region: 'Bourgogne-FC',
    habitatType: 'Hêtraie-chênaie acide, quelques résineux',
    mainMushrooms: 'Cèpes +++ (très réputé), girolles, trompettes, chanterelles en tube, pieds de mouton, bolets bai',
    mainPlants: 'Ail des ours, ortie, épilobe, myrtilles',
    mainBerries: 'Myrtilles, framboises, châtaignes +++, mûres',
    bestPeriod: 'Sep-Nov',
    notes: 'LE spot à cèpes de Bourgogne. Sols granitiques acides. Autour de Saulieu, Château-Chinon.',
    lat: 47.1,
    lng: 4,
  },
  {
    id: 'cotes-viticoles-cote-d-or',
    name: 'Côtes viticoles (Côte-d\'Or)',
    department: 'Côte-d\'Or (21)',
    region: 'Bourgogne-FC',
    habitatType: 'Boisements des côtes, sols calcaires',
    mainMushrooms: 'Truffes de Bourgogne +++ (T. uncinatum), morilles, russules',
    mainPlants: 'Ail des ours (combes), prunelles, aubépine',
    mainBerries: 'Prunelles, cynorhodons, noisettes',
    bestPeriod: 'Oct-Dec (truffes), Avr-Mai (morilles)',
    notes: 'Grande région trufficole. Hautes-Côtes de Beaune et de Nuits.',
    lat: 47.2,
    lng: 4.95,
  },
  {
    id: 'foret-de-troncais',
    name: 'Forêt de Tronçais',
    department: 'Allier (03)',
    region: 'Bourgogne-FC',
    areaHectares: 10600,
    habitatType: 'Chênaie sessiliflore cathédrale',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, pieds de mouton, russules',
    mainPlants: 'Ail des ours, muguet, violettes',
    mainBerries: 'Châtaignes, mûres, noisettes, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'L\'une des plus belles chênaies d\'Europe. Chênes de 300+ ans.',
    lat: 46.65,
    lng: 2.72,
  },
  {
    id: 'foret-de-citeaux',
    name: 'Forêt de Cîteaux',
    department: 'Côte-d\'Or (21)',
    region: 'Bourgogne-FC',
    habitatType: 'Chênaie-hêtraie',
    mainMushrooms: 'Cèpes, girolles, trompettes, morilles (printemps)',
    mainPlants: 'Ail des ours, muguet, ortie',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Forêt de l\'abbaye de Cîteaux.',
    lat: 47.08,
    lng: 5.08,
  },
  {
    id: 'haut-jura',
    name: 'Haut-Jura',
    department: 'Jura (39)',
    region: 'Bourgogne-FC',
    habitatType: 'Sapinière-pessière, alpages',
    mainMushrooms: 'Chanterelles en tube, girolles, pieds de mouton, hygrophore de mars, bolets élégants',
    mainPlants: 'Myrtilles, gentiane jaune, oxalis, épilobe',
    mainBerries: 'Myrtilles +++, airelles, framboises',
    bestPeriod: 'Jul-Août (myrtilles), Sep-Nov (champignons)',
    notes: 'Altitude 800-1700m. Région des lacs. Gentiane (récolte réglementée).',
    lat: 46.4,
    lng: 5.95,
  },
  {
    id: 'foret-de-pontarlier-risoux',
    name: 'Forêt de Pontarlier / Risoux',
    department: 'Doubs (25)',
    region: 'Bourgogne-FC',
    habitatType: 'Pessière, sapinière, altitude',
    mainMushrooms: 'Chanterelles en tube, pieds de mouton, hygrophore de mars',
    mainPlants: 'Gentiane, oxalis, myrtilles',
    mainBerries: 'Myrtilles, airelles',
    bestPeriod: 'Jul-Nov',
    notes: 'Frontière suisse. Altitude 1000-1400m.',
    lat: 46.9,
    lng: 6.38,
  },
  {
    id: 'auxois-chatillonnais',
    name: 'Auxois / Châtillonnais',
    department: 'Côte-d\'Or (21)',
    region: 'Bourgogne-FC',
    habitatType: 'Chênaie-charmaie calcaire',
    mainMushrooms: 'Morilles +++ (vallées), truffes de Bourgogne, girolles',
    mainPlants: 'Ail des ours, berce, primevères',
    mainBerries: 'Prunelles, cynorhodons, noix',
    bestPeriod: 'Avr-Mai (morilles)',
    notes: 'Sources de la Seine à proximité. Sols calcaires = morilles.',
    lat: 47.55,
    lng: 4.55,
  },
  {
    id: 'foret-d-orleans',
    name: 'Forêt d\'Orléans',
    department: 'Loiret (45)',
    region: 'Centre-VdL',
    areaHectares: 35000,
    habitatType: 'Chênaie-pinède, sols sableux',
    mainMushrooms: 'Cèpes +++, girolles, bolets jaunes, lactaires, coulemelles, russules',
    mainPlants: 'Ortie, pissenlit, bruyère',
    mainBerries: 'Mûres, noisettes, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus grande forêt domaniale de France métropolitaine.',
    lat: 47.95,
    lng: 2.15,
  },
  {
    id: 'sologne',
    name: 'Sologne',
    department: 'Loir-et-Cher (41)',
    region: 'Centre-VdL',
    areaHectares: 500000,
    habitatType: 'Pinède, chênaie sur sable, étangs',
    mainMushrooms: 'Cèpes +++, girolles, bolets bai, lactaires, russules, coulemelles',
    mainPlants: 'Ortie, bruyère (non comestible), genêt',
    mainBerries: 'Mûres, myrtilles (localisées), châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Immense zone. Sols sableux acides, étangs. Beaucoup de propriétés PRIVÉES.',
    lat: 47.55,
    lng: 1.88,
  },
  {
    id: 'foret-de-chambord',
    name: 'Forêt de Chambord',
    department: 'Loir-et-Cher (41)',
    region: 'Centre-VdL',
    areaHectares: 5440,
    habitatType: 'Chênaie-pinède, parc clos',
    mainMushrooms: 'Cèpes, girolles, bolets, lactaires',
    mainPlants: 'Ortie, fougère',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Domaine national. Accès réglementé, cueillette interdite dans le parc clos.',
    lat: 47.62,
    lng: 1.52,
  },
  {
    id: 'foret-de-chinon',
    name: 'Forêt de Chinon',
    department: 'Indre-et-Loire (37)',
    region: 'Centre-VdL',
    areaHectares: 5100,
    habitatType: 'Chênaie-pinède sur sable',
    mainMushrooms: 'Cèpes, girolles, bolets jaunes, lactaires',
    mainPlants: 'Ortie, genêt',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Sols sableux. Pinède productive en bolets.',
    lat: 47.15,
    lng: 0.25,
  },
  {
    id: 'vallee-de-la-loire-ripisylve',
    name: 'Vallée de la Loire (ripisylve)',
    department: 'Multi-départements',
    region: 'Centre-VdL',
    habitatType: 'Frênaie, peupleraie, ripisylve',
    mainMushrooms: 'Morilles (sous frênes), pleurotes, pholiotes',
    mainPlants: 'Ortie, menthe, cresson, reine-des-prés',
    mainBerries: 'Mûres, sureau noir, prunelles',
    bestPeriod: 'Avr-Mai (morilles)',
    notes: 'Le long de la Loire. Frênes + peupliers = morilles.',
    lat: 47.4,
    lng: 1.5,
  },
  {
    id: 'foret-de-boulogne-berry',
    name: 'Forêt de Boulogne (Berry)',
    department: 'Indre (36)',
    region: 'Centre-VdL',
    areaHectares: 5000,
    habitatType: 'Chênaie-charmaie',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton',
    mainPlants: 'Ail des ours (localisé), ortie',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Berry profond, peu fréquentée.',
    lat: 46.8,
    lng: 1.9,
  },
  {
    id: 'foret-de-marchenoir',
    name: 'Forêt de Marchenoir',
    department: 'Loir-et-Cher (41)',
    region: 'Centre-VdL',
    areaHectares: 5000,
    habitatType: 'Chênaie',
    mainMushrooms: 'Cèpes, girolles, pieds de mouton',
    mainPlants: 'Ail des ours, muguet',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Grande forêt beauceronne.',
    lat: 47.88,
    lng: 1.28,
  },
  {
    id: 'foret-des-landes-de-gascogne',
    name: 'Forêt des Landes de Gascogne',
    department: 'Landes / Gironde',
    region: 'Nouvelle-Aquitaine',
    areaHectares: 1000000,
    habitatType: 'Pinède maritime sur sable',
    mainMushrooms: 'Cèpes +++ (mythique), cèpes des pins, bolets jaunes, bolets granulés, lactaires délicieux',
    mainPlants: 'Ortie (lisières), bruyère',
    mainBerries: 'Mûres (lisières)',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus grande forêt artificielle d\'Europe. LE terrain à cèpes.',
    lat: 44.3,
    lng: -0.9,
  },
  {
    id: 'perigord-noir-forets',
    name: 'Périgord Noir (forêts)',
    department: 'Dordogne (24)',
    region: 'Nouvelle-Aquitaine',
    habitatType: 'Chênaie pubescente, sols calcaires, causses',
    mainMushrooms: 'Truffe noire du Périgord +++ (T. melanosporum), cèpes +++, girolles, oronges',
    mainPlants: 'Pissenlit, ortie, noyer (feuilles tisane)',
    mainBerries: 'Noix +++, châtaignes, mûres, figues sauvages',
    bestPeriod: 'Dec-Mar (truffes), Sep-Nov (cèpes)',
    notes: 'Capitale mondiale de la truffe noire. Marché de Sainte-Alvère, Sorges.',
    lat: 44.9,
    lng: 1.2,
  },
  {
    id: 'foret-de-la-double',
    name: 'Forêt de la Double',
    department: 'Dordogne (24)',
    region: 'Nouvelle-Aquitaine',
    areaHectares: 50000,
    habitatType: 'Chênaie-châtaigneraie, étangs',
    mainMushrooms: 'Cèpes +++, girolles, bolets bai, trompettes',
    mainPlants: 'Ortie, fougère',
    mainBerries: 'Mûres, châtaignes +++',
    bestPeriod: 'Sep-Nov',
    notes: 'Zone humide boisée entre Isle et Dronne.',
    lat: 45.08,
    lng: 0.28,
  },
  {
    id: 'foret-de-mouliere',
    name: 'Forêt de Moulière',
    department: 'Vienne (86)',
    region: 'Nouvelle-Aquitaine',
    areaHectares: 6800,
    habitatType: 'Chênaie-pinède, sols sableux',
    mainMushrooms: 'Cèpes, girolles, bolets, lactaires',
    mainPlants: 'Ortie, bruyère, genêt',
    mainBerries: 'Mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Sols sableux productifs.',
    lat: 46.68,
    lng: 0.48,
  },
  {
    id: 'plateau-de-millevaches',
    name: 'Plateau de Millevaches',
    department: 'Corrèze / Creuse',
    region: 'Nouvelle-Aquitaine',
    habitatType: 'Hêtraie, landes, tourbières',
    mainMushrooms: 'Cèpes +++, girolles, chanterelles en tube, trompettes',
    mainPlants: 'Myrtilles, épilobe, gentiane (rare)',
    mainBerries: 'Myrtilles, airelles (tourbières)',
    bestPeriod: 'Sep-Nov',
    notes: 'Zone peu peuplée, altitude 800-1000m. Excellente zone à cèpes.',
    lat: 45.65,
    lng: 2.05,
  },
  {
    id: 'foret-de-chalus-monts-de-chalus',
    name: 'Forêt de Châlus / Monts de Châlus',
    department: 'Haute-Vienne (87)',
    region: 'Nouvelle-Aquitaine',
    habitatType: 'Châtaigneraie-chênaie',
    mainMushrooms: 'Cèpes +++, girolles, oronges (rares), trompettes',
    mainPlants: 'Ortie, ortie, pissenlit',
    mainBerries: 'Châtaignes +++, mûres',
    bestPeriod: 'Sep-Nov',
    notes: 'Limousin = terre à cèpes.',
    lat: 45.65,
    lng: 0.95,
  },
  {
    id: 'foret-d-horte',
    name: 'Forêt d\'Horte',
    department: 'Charente (16)',
    region: 'Nouvelle-Aquitaine',
    areaHectares: 4000,
    habitatType: 'Chênaie calcaire',
    mainMushrooms: 'Cèpes, truffes (localement), girolles',
    mainPlants: 'Ail des ours, ortie',
    mainBerries: 'Noisettes, mûres, prunelles',
    bestPeriod: 'Sep-Nov',
    notes: 'Sols calcaires charentais.',
    lat: 45.72,
    lng: 0.28,
  },
  {
    id: 'bassin-d-arcachon-pres-sales',
    name: 'Bassin d\'Arcachon (prés salés)',
    department: 'Gironde (33)',
    region: 'Nouvelle-Aquitaine',
    habitatType: 'Prés salés, estran, dunes',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne +++, obione, aster maritime, criste marine',
    mainBerries: 'Argousier (rares)',
    bestPeriod: 'Jun-Sep',
    notes: 'Zone de cueillette traditionnelle. Réglementation.',
    lat: 44.65,
    lng: -1.15,
  },
  {
    id: 'ile-de-re-estran-marais',
    name: 'Île de Ré (estran / marais)',
    department: 'Charente-Maritime (17)',
    region: 'Nouvelle-Aquitaine',
    habitatType: 'Estran, marais salants',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne +++, algues, criste marine',
    mainBerries: 'Aucun',
    bestPeriod: 'Jun-Sep',
    notes: 'Marais salants, estran riche. Tradition locale.',
    lat: 46.2,
    lng: -1.4,
  },
  {
    id: 'ile-d-oleron',
    name: 'Île d\'Oléron',
    department: 'Charente-Maritime (17)',
    region: 'Nouvelle-Aquitaine',
    habitatType: 'Forêt dunaire, marais, estran',
    mainMushrooms: 'Bolets (pinède dunaire), lactaires',
    mainPlants: 'Salicorne, immortelle (non comestible), criste marine',
    mainBerries: 'Mûres, argousier',
    bestPeriod: 'Jun-Sep (littoral), Sep-Nov (forêt)',
    notes: 'Forêt de pins + estran. Double intérêt.',
    lat: 45.9,
    lng: -1.3,
  },
  {
    id: 'foret-de-rochechouart',
    name: 'Forêt de Rochechouart',
    department: 'Haute-Vienne (87)',
    region: 'Nouvelle-Aquitaine',
    habitatType: 'Chênaie sur sol de météorite',
    mainMushrooms: 'Cèpes, girolles',
    mainPlants: 'Ortie, fougère',
    mainBerries: 'Mûres, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Cratère d\'impact de météorite ! Sol unique.',
    lat: 45.82,
    lng: 0.82,
  },
  {
    id: 'cevennes-mont-lozere',
    name: 'Cévennes / Mont Lozère',
    department: 'Gard / Lozère',
    region: 'Occitanie',
    habitatType: 'Châtaigneraie ancestrale, hêtraie',
    mainMushrooms: 'Cèpes +++, girolles, oronges (versant sud), lactaires sanglants',
    mainPlants: 'Châtaignier (tisane), ortie, thym (garrigue)',
    mainBerries: 'Châtaignes +++ (récolte majeure), mûres, myrtilles, framboises',
    bestPeriod: 'Sep-Nov (cèpes), Oct (châtaignes)',
    notes: 'Châtaigneraie ancestrale cévenole. Parc National.',
    lat: 44.3,
    lng: 3.6,
  },
  {
    id: 'montagne-noire',
    name: 'Montagne Noire',
    department: 'Tarn / Aude',
    region: 'Occitanie',
    habitatType: 'Hêtraie-chênaie, châtaigneraie',
    mainMushrooms: 'Cèpes +++, girolles, oronges (versant sud), trompettes, lactaires',
    mainPlants: 'Ortie, thym, romarin (sud)',
    mainBerries: 'Châtaignes, mûres, myrtilles (crêtes)',
    bestPeriod: 'Sep-Nov',
    notes: 'Transition méditerranéen/atlantique. Sols acides.',
    lat: 43.42,
    lng: 2.35,
  },
  {
    id: 'causses-du-larzac',
    name: 'Causses du Larzac',
    department: 'Aveyron / Hérault',
    region: 'Occitanie',
    habitatType: 'Pelouses calcaires, chênaie pubescente, dolines',
    mainMushrooms: 'Morilles +++ (dolines karstiques), truffes d\'été, rosés des prés',
    mainPlants: 'Thym, romarin, genévrier, lavande',
    mainBerries: 'Prunelles, genévrier (baies), cynorhodons',
    bestPeriod: 'Avr-Mai (morilles), Sep-Nov',
    notes: 'Dolines karstiques = spots à morilles légendaires.',
    lat: 43.8,
    lng: 3.2,
  },
  {
    id: 'aubrac',
    name: 'Aubrac',
    department: 'Aveyron / Lozère',
    region: 'Occitanie',
    habitatType: 'Hêtraie, prairies d\'altitude 1000-1400m',
    mainMushrooms: 'Mousserons de Saint-Georges +++, rosés des prés, cèpes (bordures)',
    mainPlants: 'Gentiane jaune +++, thé d\'Aubrac, narcisses (non comestibles)',
    mainBerries: 'Myrtilles, airelles',
    bestPeriod: 'Mai (mousserons), Sep-Oct (cèpes)',
    notes: 'Plateau granitique. Gentiane = tradition locale (liqueur).',
    lat: 44.65,
    lng: 2.95,
  },
  {
    id: 'haut-languedoc-espinouse',
    name: 'Haut-Languedoc (Espinouse)',
    department: 'Hérault / Tarn',
    region: 'Occitanie',
    habitatType: 'Hêtraie, châtaigneraie, résineux',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, oronges',
    mainPlants: 'Bruyère, châtaignier (tisane), thym',
    mainBerries: 'Châtaignes, myrtilles (Espinouse), mûres',
    bestPeriod: 'Sep-Nov',
    notes: 'Monts de l\'Espinouse : myrtilles + cèpes.',
    lat: 43.58,
    lng: 2.8,
  },
  {
    id: 'corbieres',
    name: 'Corbières',
    department: 'Aude (11)',
    region: 'Occitanie',
    habitatType: 'Garrigue, pinède, maquis',
    mainMushrooms: 'Lactaires sanglants, oronges, cèpes (altitude), truffe d\'été',
    mainPlants: 'Romarin +++, thym +++, fenouil, asperge sauvage',
    mainBerries: 'Arbouses (localisées), mûres',
    bestPeriod: 'Oct-Nov',
    notes: 'Relief accidenté, garrigues odorantes.',
    lat: 42.95,
    lng: 2.55,
  },
  {
    id: 'foret-d-iraty',
    name: 'Forêt d\'Iraty',
    department: 'Pyrénées-Atlantiques (64)',
    region: 'Nouvelle-Aquitaine',
    areaHectares: 17000,
    habitatType: 'Hêtraie ancestrale, la plus grande d\'Europe',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, pieds de mouton, chanterelles en tube',
    mainPlants: 'Myrtilles, fougères, oxalis',
    mainBerries: 'Myrtilles +++, framboises, airelles',
    bestPeriod: 'Jul-Août (myrtilles), Sep-Nov (cèpes)',
    notes: 'Plus grande hêtraie d\'Europe. Altitude 1000-1500m. Mythique.',
    lat: 43.05,
    lng: -1.05,
  },
  {
    id: 'pyrenees-centrales-luchonnais',
    name: 'Pyrénées centrales (Luchonnais)',
    department: 'Haute-Garonne / Ariège',
    region: 'Occitanie',
    habitatType: 'Hêtraie-sapinière, alpages',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, chanterelles en tube, hygrophore de mars',
    mainPlants: 'Génépi, gentiane, épilobe, myrtilles',
    mainBerries: 'Myrtilles +++, framboises, airelles',
    bestPeriod: 'Jul-Août (myrtilles), Sep-Nov (champignons)',
    notes: 'Vallée du Luchonnais très réputée. Altitude 800-2000m.',
    lat: 42.8,
    lng: 0.6,
  },
  {
    id: 'lot-quercy-causses',
    name: 'Lot / Quercy (causses)',
    department: 'Lot (46)',
    region: 'Occitanie',
    habitatType: 'Chênaie pubescente, causses calcaires',
    mainMushrooms: 'Truffes noires +++, truffe d\'été, morilles, oronges (rares), girolles',
    mainPlants: 'Thym, genévrier, fenouil',
    mainBerries: 'Noix +++, prunelles, cynorhodons, genévrier',
    bestPeriod: 'Dec-Mar (truffes), Avr-Mai (morilles)',
    notes: 'Causses = truffes. Marché de Lalbenque (mardi en hiver).',
    lat: 44.5,
    lng: 1.5,
  },
  {
    id: 'foret-de-gresigne',
    name: 'Forêt de Grésigne',
    department: 'Tarn (81)',
    region: 'Occitanie',
    areaHectares: 3500,
    habitatType: 'Chênaie sessiliflore ancienne',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, oronges',
    mainPlants: 'Ail des ours, ortie, violettes',
    mainBerries: 'Mûres, noisettes, châtaignes',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus grande forêt du Tarn. Chênes magnifiques.',
    lat: 44.02,
    lng: 1.72,
  },
  {
    id: 'etangs-littoraux-thau-leucate',
    name: 'Étangs littoraux (Thau, Leucate)',
    department: 'Hérault / Aude',
    region: 'Occitanie',
    habitatType: 'Lagunes, prés salés, sansouïres',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne, soude, obione, criste marine',
    mainBerries: 'Aucun',
    bestPeriod: 'Jun-Sep',
    notes: 'Étangs saumâtres méditerranéens.',
    lat: 43.4,
    lng: 3.6,
  },
  {
    id: 'gers-gascogne-bocage',
    name: 'Gers / Gascogne (bocage)',
    department: 'Gers (32)',
    region: 'Occitanie',
    habitatType: 'Chênaie, haies bocagères, coteaux',
    mainMushrooms: 'Cèpes, girolles, rosés des prés, coulemelles',
    mainPlants: 'Ortie, pissenlit, roquette',
    mainBerries: 'Noix, mûres, prunelles, sureau noir',
    bestPeriod: 'Sep-Nov',
    notes: 'Bocage gersois. Haies riches en prunelles et sureau.',
    lat: 43.65,
    lng: 0.58,
  },
  {
    id: 'vallee-de-l-ariege-foret-de-belesta',
    name: 'Vallée de l\'Ariège / Forêt de Bélesta',
    department: 'Ariège (09)',
    region: 'Occitanie',
    areaHectares: 2500,
    habitatType: 'Hêtraie-sapinière, grotte',
    mainMushrooms: 'Cèpes, girolles, trompettes, chanterelles',
    mainPlants: 'Ortie, ail des ours, oxalis',
    mainBerries: 'Myrtilles, framboises, mûres',
    bestPeriod: 'Sep-Nov',
    notes: 'Pyrénées ariégeoises. Grotte de la Vache à côté.',
    lat: 42.88,
    lng: 1.95,
  },
  {
    id: 'monts-du-cantal',
    name: 'Monts du Cantal',
    department: 'Cantal (15)',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie-sapinière, estives',
    mainMushrooms: 'Cèpes +++, girolles, trompettes, morilles (localement), chanterelles en tube',
    mainPlants: 'Gentiane jaune +++, épilobe, myrtilles',
    mainBerries: 'Myrtilles +++, framboises, airelles',
    bestPeriod: 'Jul-Sep (myrtilles), Sep-Nov (champignons)',
    notes: 'Excellent territoire à cèpes. Altitude 800-1800m. Salers, Aurillac.',
    lat: 45.3,
    lng: 2.8,
  },
  {
    id: 'chaine-des-puys',
    name: 'Chaîne des Puys',
    department: 'Puy-de-Dôme (63)',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie, résineux, coulées de lave',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton',
    mainPlants: 'Gentiane, épilobe, thym',
    mainBerries: 'Myrtilles, framboises, mûres',
    bestPeriod: 'Sep-Nov',
    notes: 'UNESCO. Sols volcaniques intéressants.',
    lat: 45.78,
    lng: 2.95,
  },
  {
    id: 'foret-de-la-comte',
    name: 'Forêt de la Comté',
    department: 'Puy-de-Dôme (63)',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie-sapinière',
    mainMushrooms: 'Cèpes +++, girolles, chanterelles en tube',
    mainPlants: 'Ail des ours, oxalis',
    mainBerries: 'Myrtilles, framboises',
    bestPeriod: 'Sep-Nov',
    notes: 'Réputée localement pour les cèpes.',
    lat: 45.62,
    lng: 3.15,
  },
  {
    id: 'livradois-forez',
    name: 'Livradois-Forez',
    department: 'PdD / Haute-Loire',
    region: 'Auvergne-RA',
    habitatType: 'Sapinière-pessière, hêtraie',
    mainMushrooms: 'Cèpes, girolles, chanterelles en tube, pieds de mouton',
    mainPlants: 'Gentiane, myrtilles, épilobe',
    mainBerries: 'Myrtilles +++, framboises, airelles',
    bestPeriod: 'Jul-Nov',
    notes: 'Montagnes moyennes 600-1600m. Très riche.',
    lat: 45.5,
    lng: 3.6,
  },
  {
    id: 'ardeche-vallees-et-plateaux',
    name: 'Ardèche (vallées et plateaux)',
    department: 'Ardèche (07)',
    region: 'Auvergne-RA',
    habitatType: 'Châtaigneraie, chênaie, garrigue',
    mainMushrooms: 'Cèpes +++, oronges +++, girolles, lactaires',
    mainPlants: 'Thym (sud), romarin (sud), ortie',
    mainBerries: 'Châtaignes +++ (tradition ardéchoise), mûres, figues (sud)',
    bestPeriod: 'Sep-Nov',
    notes: 'Terrain escarpé. Oronges en versant sud. Châtaignes : fête à Joyeuse.',
    lat: 44.65,
    lng: 4.35,
  },
  {
    id: 'monts-du-lyonnais',
    name: 'Monts du Lyonnais',
    department: 'Rhône (69)',
    region: 'Auvergne-RA',
    habitatType: 'Chênaie-châtaigneraie',
    mainMushrooms: 'Cèpes, girolles, trompettes, pieds de mouton',
    mainPlants: 'Ail des ours, ortie, pissenlit',
    mainBerries: 'Châtaignes, mûres, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Proche Lyon, facilement accessible.',
    lat: 45.65,
    lng: 4.45,
  },
  {
    id: 'pilat',
    name: 'Pilat',
    department: 'Loire / Rhône',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie-sapinière, landes',
    mainMushrooms: 'Cèpes, girolles, chanterelles en tube, pieds de mouton',
    mainPlants: 'Myrtilles, gentiane, épilobe',
    mainBerries: 'Myrtilles, framboises',
    bestPeriod: 'Sep-Nov',
    notes: 'Altitude 700-1400m. Parc naturel régional.',
    lat: 45.37,
    lng: 4.55,
  },
  {
    id: 'bugey-ain-plateaux-calcaires',
    name: 'Bugey / Ain (plateaux calcaires)',
    department: 'Ain (01)',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie, chênaie calcaire',
    mainMushrooms: 'Morilles +++ (sols calcaires + frênes), trompettes, pieds de mouton, girolles',
    mainPlants: 'Ail des ours +++, ortie, berce',
    mainBerries: 'Noisettes, mûres, prunelles',
    bestPeriod: 'Avr-Mai (morilles), Sep-Nov',
    notes: 'Excellent terrain à morilles (calcaire + frênes + humidité).',
    lat: 45.9,
    lng: 5.5,
  },
  {
    id: 'chartreuse',
    name: 'Chartreuse',
    department: 'Isère / Savoie',
    region: 'Auvergne-RA',
    habitatType: 'Sapinière-hêtraie, falaises calcaires',
    mainMushrooms: 'Cèpes, girolles +++, trompettes, chanterelles en tube, pieds de mouton, hygrophore de mars',
    mainPlants: 'Ail des ours, gentiane, aspérule',
    mainBerries: 'Framboises, myrtilles, fraises des bois',
    bestPeriod: 'Sep-Nov',
    notes: 'Forêts profondes et humides. Altitude 500-2000m.',
    lat: 45.35,
    lng: 5.8,
  },
  {
    id: 'bauges',
    name: 'Bauges',
    department: 'Savoie / Haute-Savoie',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie-sapinière, alpages',
    mainMushrooms: 'Cèpes, girolles, chanterelles en tube, trompettes, pieds de mouton, bolets élégants',
    mainPlants: 'Ail des ours, gentiane, arnica (protégée)',
    mainBerries: 'Myrtilles, framboises, airelles',
    bestPeriod: 'Sep-Oct',
    notes: 'Massif préservé. Alpages riches.',
    lat: 45.62,
    lng: 6.15,
  },
  {
    id: 'vercors',
    name: 'Vercors',
    department: 'Drôme / Isère',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie-sapinière, falaises, forêt de Lente',
    mainMushrooms: 'Morilles +++, trompettes, pieds de mouton, cèpes (versant ouest)',
    mainPlants: 'Ail des ours, gentiane, lavande (bordure sud)',
    mainBerries: 'Framboises, myrtilles, noisettes',
    bestPeriod: 'Avr-Mai (morilles), Sep-Nov',
    notes: 'Forêt de Lente réputée. Altitude 800-1700m.',
    lat: 44.95,
    lng: 5.45,
  },
  {
    id: 'belledonne',
    name: 'Belledonne',
    department: 'Isère (38)',
    region: 'Auvergne-RA',
    habitatType: 'Sapinière, mélézin, alpages',
    mainMushrooms: 'Cèpes, girolles, chanterelles en tube, bolets élégants',
    mainPlants: 'Myrtilles, génépi, épilobe',
    mainBerries: 'Myrtilles +++, framboises, airelles',
    bestPeriod: 'Jul-Oct',
    notes: 'Altitude 500-2500m. Versant Grésivaudan.',
    lat: 45.2,
    lng: 6.02,
  },
  {
    id: 'vanoise-vallees-basses',
    name: 'Vanoise (vallées basses)',
    department: 'Savoie (73)',
    region: 'Auvergne-RA',
    habitatType: 'Mélézin, sapinière',
    mainMushrooms: 'Bolets élégants, chanterelles en tube, lactaires',
    mainPlants: 'Génépi +++, myrtilles, oxalis',
    mainBerries: 'Myrtilles, airelles, framboises',
    bestPeriod: 'Jul-Oct',
    notes: 'Zone cœur du Parc : cueillette interdite. Vallées en bordure OK.',
    lat: 45.35,
    lng: 6.72,
  },
  {
    id: 'drome-provencale-tricastin',
    name: 'Drôme provençale (Tricastin)',
    department: 'Drôme (26)',
    region: 'Auvergne-RA',
    habitatType: 'Chênaie pubescente, truffière',
    mainMushrooms: 'Truffe noire +++ (T. melanosporum), truffe d\'été',
    mainPlants: 'Thym +++, romarin, sarriette, lavande (non comestible)',
    mainBerries: 'Amandes (vergers), olives',
    bestPeriod: 'Dec-Mar (truffes)',
    notes: 'Zone trufficole majeure. Marché de Richerenches (samedi matin en hiver).',
    lat: 44.35,
    lng: 4.9,
  },
  {
    id: 'plateau-de-millevaches-versant-auvergnat',
    name: 'Plateau de Millevaches versant auvergnat',
    department: 'Puy-de-Dôme / Cantal',
    region: 'Auvergne-RA',
    habitatType: 'Hêtraie, tourbières',
    mainMushrooms: 'Cèpes, girolles, chanterelles en tube',
    mainPlants: 'Myrtilles, canneberge (tourbières)',
    mainBerries: 'Myrtilles, airelles, canneberge',
    bestPeriod: 'Sep-Nov',
    notes: 'Prolongement auvergnat du plateau.',
    lat: 45.55,
    lng: 2.5,
  },
  {
    id: 'mont-ventoux',
    name: 'Mont Ventoux',
    department: 'Vaucluse (84)',
    region: 'PACA',
    habitatType: 'Chênaie verte → hêtraie → résineux (étagement complet)',
    mainMushrooms: 'Truffe noire (pied sud), cèpes, girolles (altitude), lactaires',
    mainPlants: 'Thym +++, romarin, lavande, sarriette, fenouil',
    mainBerries: 'Genévrier (baies), mûres',
    bestPeriod: 'Dec-Mar (truffes), Sep-Nov (champignons)',
    notes: 'Étagement méditerranéen → montagnard sur un seul versant.',
    lat: 44.17,
    lng: 5.28,
  },
  {
    id: 'luberon-plateau-d-albion',
    name: 'Luberon / Plateau d\'Albion',
    department: 'Vaucluse / AHP',
    region: 'PACA',
    habitatType: 'Chênaie pubescente, garrigue haute, truffière',
    mainMushrooms: 'Truffe noire +++ (Apt, Carpentras), truffe d\'été, lactaires',
    mainPlants: 'Thym, romarin, sarriette, lavande, fenouil, asperge sauvage',
    mainBerries: 'Amandes, figues, olives',
    bestPeriod: 'Dec-Mar (truffes), Mai-Août (truffe été)',
    notes: 'Haut-lieu trufficole. Truffières de chênes plantées.',
    lat: 43.95,
    lng: 5.35,
  },
  {
    id: 'massif-des-maures',
    name: 'Massif des Maures',
    department: 'Var (83)',
    region: 'PACA',
    habitatType: 'Maquis, chênaie liège, châtaigneraie',
    mainMushrooms: 'Oronges +++, cèpes bronzés +++, lactaires sanglants',
    mainPlants: 'Myrte, asperge sauvage, fenouil',
    mainBerries: 'Arbouses +++, châtaignes (Collobrières), mûres',
    bestPeriod: 'Oct-Nov (oronges, cèpes), Nov-Dec (arbouses)',
    notes: 'Sols acides siliceux. Collobrières = capitale de la châtaigne.',
    lat: 43.4,
    lng: 6.2,
  },
  {
    id: 'massif-de-l-esterel',
    name: 'Massif de l\'Esterel',
    department: 'Var / Alpes-Maritimes',
    region: 'PACA',
    habitatType: 'Maquis, pinède sur porphyre rouge',
    mainMushrooms: 'Oronges, lactaires, bolets',
    mainPlants: 'Myrte, romarin, bruyère',
    mainBerries: 'Arbouses, mûres',
    bestPeriod: 'Oct-Nov',
    notes: 'Roches rouges spectaculaires. Sols acides.',
    lat: 43.48,
    lng: 6.8,
  },
  {
    id: 'alpilles',
    name: 'Alpilles',
    department: 'Bouches-du-Rhône (13)',
    region: 'PACA',
    habitatType: 'Garrigue, chênaie verte, pinède',
    mainMushrooms: 'Lactaires (sous pins), pleurote du panicaut (Crau)',
    mainPlants: 'Thym +++, romarin +++, fenouil, asperge sauvage, câprier (rare)',
    mainBerries: 'Olives (sauvages), amandes',
    bestPeriod: 'Oct-Nov',
    notes: 'Les Baux-de-Provence. Pleurote du panicaut spécifique de la Crau.',
    lat: 43.72,
    lng: 4.82,
  },
  {
    id: 'camargue',
    name: 'Camargue',
    department: 'Bouches-du-Rhône (13)',
    region: 'PACA',
    habitatType: 'Delta, prés salés, sansouïres',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne +++, soude, obione, saladelle',
    mainBerries: 'Aucun',
    bestPeriod: 'Jun-Sep',
    notes: 'Zone protégée. Cueillette très réglementée.',
    lat: 43.5,
    lng: 4.5,
  },
  {
    id: 'haute-provence-verdon',
    name: 'Haute-Provence (Verdon)',
    department: 'AHP (04)',
    region: 'PACA',
    habitatType: 'Chênaie pubescente, pinède, lavande',
    mainMushrooms: 'Truffe d\'été, lactaires, cèpes (altitude)',
    mainPlants: 'Lavande +++, thym, romarin, sarriette, sauge',
    mainBerries: 'Amandes, genévrier, prunelles',
    bestPeriod: 'Sep-Nov',
    notes: 'Gorges du Verdon à proximité. Lavande de Valensole.',
    lat: 43.8,
    lng: 6.2,
  },
  {
    id: 'mercantour-vallees-basses',
    name: 'Mercantour (vallées basses)',
    department: 'AHP / AM',
    region: 'PACA',
    habitatType: 'Mélézin, sapinière',
    mainMushrooms: 'Cèpes, girolles, bolets élégants, chanterelles',
    mainPlants: 'Génépi, gentiane, myrtilles',
    mainBerries: 'Myrtilles, framboises, airelles',
    bestPeriod: 'Jul-Oct',
    notes: 'Zone cœur : cueillette très réglementée/interdite. Vallées OK.',
    lat: 44.1,
    lng: 6.95,
  },
  {
    id: 'foret-de-la-sainte-baume',
    name: 'Forêt de la Sainte-Baume',
    department: 'Var / BdR',
    region: 'PACA',
    habitatType: 'Hêtraie relicte en versant nord, garrigue versant sud',
    mainMushrooms: 'Cèpes (versant nord), girolles, trompettes, lactaires (versant sud)',
    mainPlants: 'Ail des ours (versant nord), thym, romarin (versant sud)',
    mainBerries: 'Mûres, arbouses (versant sud)',
    bestPeriod: 'Sep-Nov',
    notes: 'Hêtraie relicte unique en Provence. Lieu sacré.',
    lat: 43.33,
    lng: 5.78,
  },
  {
    id: 'iles-de-lerins-esterel-littoral',
    name: 'Îles de Lérins / Estérel littoral',
    department: 'AM (06)',
    region: 'PACA',
    habitatType: 'Estran, pinède littorale',
    mainMushrooms: 'Aucun',
    mainPlants: 'Criste marine, fenouil marin',
    mainBerries: 'Figues sauvages, mûres',
    bestPeriod: 'Jun-Sep (criste marine)',
    notes: 'Littoral méditerranéen. Criste marine sur rochers.',
    lat: 43.52,
    lng: 6.98,
  },
  {
    id: 'foret-de-vizzavona',
    name: 'Forêt de Vizzavona',
    department: 'Haute-Corse (2B)',
    region: 'Corse',
    areaHectares: 1600,
    habitatType: 'Hêtraie + pinède (pin laricio endémique)',
    mainMushrooms: 'Cèpes +++, oronges +++, lactaires sanglants, girolles',
    mainPlants: 'Fougère, mousse, ortie',
    mainBerries: 'Châtaignes, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Pin laricio endémique. Col de Vizzavona, GR20.',
    lat: 42.12,
    lng: 9.12,
  },
  {
    id: 'foret-d-aitone',
    name: 'Forêt d\'Aïtone',
    department: 'Corse-du-Sud (2A)',
    region: 'Corse',
    areaHectares: 4600,
    habitatType: 'Pinède de pin laricio géant',
    mainMushrooms: 'Cèpes, lactaires sanglants, bolets, girolles',
    mainPlants: 'Fougère, mousse',
    mainBerries: 'Châtaignes, noisettes',
    bestPeriod: 'Sep-Nov',
    notes: 'Pins laricio géants (50m). Piscines naturelles.',
    lat: 42.15,
    lng: 8.98,
  },
  {
    id: 'foret-de-bavella',
    name: 'Forêt de Bavella',
    department: 'Corse-du-Sud (2A)',
    region: 'Corse',
    habitatType: 'Pinède de pin laricio, aiguilles',
    mainMushrooms: 'Cèpes, lactaires, bolets',
    mainPlants: 'Immortelle (non comestible), thym corse',
    mainBerries: 'Arbouses (altitude basse)',
    bestPeriod: 'Sep-Nov',
    notes: 'Aiguilles de Bavella spectaculaires. Altitude 1000-1600m.',
    lat: 41.8,
    lng: 9.22,
  },
  {
    id: 'castagniccia',
    name: 'Castagniccia',
    department: 'Haute-Corse (2B)',
    region: 'Corse',
    habitatType: 'Châtaigneraie ancestrale',
    mainMushrooms: 'Cèpes, oronges, girolles, lactaires',
    mainPlants: 'Ortie, menthe',
    mainBerries: 'Châtaignes +++ (récolte traditionnelle majeure), mûres, noisettes',
    bestPeriod: 'Oct-Nov',
    notes: 'Région historique de la châtaigne corse. \'Arbre à pain\'.',
    lat: 42.35,
    lng: 9.35,
  },
  {
    id: 'foret-de-valdu-niellu',
    name: 'Forêt de Valdu-Niellu',
    department: 'Haute-Corse (2B)',
    region: 'Corse',
    habitatType: 'Pinède de pin laricio',
    mainMushrooms: 'Cèpes, lactaires, girolles',
    mainPlants: 'Mousse, fougère',
    mainBerries: 'Châtaignes (bordures)',
    bestPeriod: 'Sep-Nov',
    notes: 'Plus haute forêt de Corse. Altitude 800-1600m.',
    lat: 42.22,
    lng: 9.02,
  },
  {
    id: 'maquis-littoral',
    name: 'Maquis littoral',
    department: 'Toute la Corse',
    region: 'Corse',
    habitatType: 'Maquis : arbousier, ciste, myrte, lentisque',
    mainMushrooms: 'Oronges (lisières), lactaires sanglants',
    mainPlants: 'Myrte +++ (baies = liqueur), fenouil, asperge sauvage, immortelle',
    mainBerries: 'Arbouses +++, figues sauvages, mûres',
    bestPeriod: 'Oct-Dec (arbouses)',
    notes: 'Myrte = liqueur traditionnelle corse. Arbouses abondantes.',
    lat: 42,
    lng: 9,
  },
  {
    id: 'cap-corse-maquis-et-estran',
    name: 'Cap Corse (maquis et estran)',
    department: 'Haute-Corse (2B)',
    region: 'Corse',
    habitatType: 'Maquis, estran rocheux',
    mainMushrooms: 'Aucun (ou oronges rares)',
    mainPlants: 'Criste marine, fenouil marin, algues',
    mainBerries: 'Figues sauvages, arbouses, olives sauvages',
    bestPeriod: 'Jun-Sep (criste), Oct-Dec (arbouses)',
    notes: 'Presqu\'île sauvage. Criste marine sur rochers côtiers.',
    lat: 42.85,
    lng: 9.35,
  },
  {
    id: 'foret-de-bonifatu',
    name: 'Forêt de Bonifatu',
    department: 'Haute-Corse (2B)',
    region: 'Corse',
    habitatType: 'Pinède de pin laricio, torrent',
    mainMushrooms: 'Cèpes, lactaires',
    mainPlants: 'Menthe sauvage (bords de torrent)',
    mainBerries: 'Mûres',
    bestPeriod: 'Sep-Nov',
    notes: 'Cirque de Bonifatu. Départ GR20.',
    lat: 42.48,
    lng: 8.88,
  },
  {
    id: 'dunes-atlantiques-landes-vendee',
    name: 'Dunes atlantiques (Landes → Vendée)',
    department: 'Côte atlantique',
    region: 'Atlantique',
    habitatType: 'Dunes fixées, pinède littorale arrière-dune',
    mainMushrooms: 'Bolets jaunes, lactaires (pinède arrière-dune)',
    mainPlants: 'Immortelle des dunes, pourpier de mer',
    mainBerries: 'Argousier (nord), mûres',
    bestPeriod: 'Sep-Nov (forêt), Jun-Sep (littoral)',
    notes: 'Pinède arrière-dune productive en bolets.',
    lat: 45.5,
    lng: -1.2,
  },
  {
    id: 'pertuis-charentais-re-oleron-aix',
    name: 'Pertuis charentais (Ré, Oléron, Aix)',
    department: 'Charente-Maritime',
    region: 'Atlantique',
    habitatType: 'Estran, marais salants, forêts dunaires',
    mainMushrooms: 'Bolets (forêt de Ré, d\'Oléron)',
    mainPlants: 'Salicorne +++, criste marine, algues',
    mainBerries: 'Mûres',
    bestPeriod: 'Jun-Sep (littoral)',
    notes: 'Marais salants traditionnels. Double cueillette mer + forêt.',
    lat: 46.1,
    lng: -1.3,
  },
  {
    id: 'cote-basque-corniche',
    name: 'Côte basque (Corniche)',
    department: 'Pyrénées-Atlantiques',
    region: 'Atlantique',
    habitatType: 'Falaises, estran, prairies littorales',
    mainMushrooms: 'Aucun',
    mainPlants: 'Criste marine, fenouil',
    mainBerries: 'Mûres, prunelles (haies)',
    bestPeriod: 'Jun-Sep',
    notes: 'Corniche basque entre Hendaye et Saint-Jean-de-Luz.',
    lat: 43.35,
    lng: -1.72,
  },
  {
    id: 'estuaire-de-la-gironde',
    name: 'Estuaire de la Gironde',
    department: 'Gironde / Charente-Maritime',
    region: 'Atlantique',
    habitatType: 'Prés salés, vasières',
    mainMushrooms: 'Aucun',
    mainPlants: 'Salicorne, obione, aster maritime',
    mainBerries: 'Aucun',
    bestPeriod: 'Jun-Sep',
    notes: 'Plus grand estuaire d\'Europe.',
    lat: 45.5,
    lng: -0.95,
  },
];
