// ============================================================
// ChampIndex — Base de données mycologique (25 espèces)
// ============================================================

import type { MushroomSpecies, Spot } from '../types';

export const SPECIES: MushroomSpecies[] = [
  // ═══════ PRINTEMPS ═══════
  {
    id: 'morille-commune',
    nom: 'Morille commune',
    latin: 'Morchella esculenta',
    emoji: '🟤',
    moisDebut: 3,
    moisFin: 5,
    tempMin: 8,
    tempMax: 18,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1200,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['frêne', 'pommier', 'orme', 'peuplier'],
    description: 'Champignon printanier très recherché, reconnaissable à son chapeau alvéolé en forme d\'éponge.',
    confusionsDangereuses: 'Gyromitre (Gyromitra esculenta) — toxique mortel. Le chapeau est en forme de cerveau, pas alvéolé.',
    comestibilite: 'excellent',
  },
  {
    id: 'morille-conique',
    nom: 'Morille conique',
    latin: 'Morchella conica',
    emoji: '🟤',
    moisDebut: 3,
    moisFin: 5,
    tempMin: 6,
    tempMax: 16,
    besoinPluie: 'modéré',
    altitudeMin: 200,
    altitudeMax: 1500,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['conifère', 'frêne', 'peuplier'],
    description: 'Morille au chapeau conique et allongé, souvent plus tardive en montagne.',
    confusionsDangereuses: 'Gyromitre (Gyromitra esculenta) — toxique mortel.',
    comestibilite: 'excellent',
  },
  {
    id: 'mousseron-st-georges',
    nom: 'Mousseron de la St-Georges',
    latin: 'Calocybe gambosa',
    emoji: '⬜',
    moisDebut: 4,
    moisFin: 6,
    tempMin: 10,
    tempMax: 20,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1000,
    expositionPreferee: 'indifférent',
    pentePreferee: 'plat',
    essences: ['prairie', 'haie', 'lisière'],
    description: 'Champignon de prairie au parfum de farine fraîche, pousse en ronds de sorcière.',
    confusionsDangereuses: 'Inocybe de Patouillard (Inocybe erubescens) — toxique grave. Pousse aux mêmes endroits au printemps.',
    comestibilite: 'excellent',
  },
  {
    id: 'coprin-chevelu',
    nom: 'Coprin chevelu',
    latin: 'Coprinus comatus',
    emoji: '⬜',
    moisDebut: 4,
    moisFin: 11,
    tempMin: 8,
    tempMax: 22,
    besoinPluie: 'élevé',
    altitudeMin: 0,
    altitudeMax: 800,
    expositionPreferee: 'indifférent',
    pentePreferee: 'plat',
    essences: ['prairie', 'pelouse', 'bord de chemin'],
    description: 'Chapeau blanc en forme de doigt qui noircit en vieillissant. À consommer très frais.',
    confusionsDangereuses: 'Coprin noir d\'encre (Coprinopsis atramentaria) — toxique avec alcool.',
    comestibilite: 'bon',
  },

  // ═══════ ÉTÉ ═══════
  {
    id: 'girolle',
    nom: 'Girolle',
    latin: 'Cantharellus cibarius',
    emoji: '🟡',
    moisDebut: 6,
    moisFin: 11,
    tempMin: 12,
    tempMax: 25,
    besoinPluie: 'élevé',
    altitudeMin: 0,
    altitudeMax: 1500,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['chêne', 'hêtre', 'châtaignier', 'épicéa'],
    description: 'Champignon jaune d\'or en forme d\'entonnoir, parfum fruité d\'abricot.',
    confusionsDangereuses: 'Clitocybe de l\'olivier (Omphalotus olearius) — toxique. Pousse en touffes sur bois mort, lamelles non fourchues.',
    comestibilite: 'excellent',
  },
  {
    id: 'cepe-ete',
    nom: 'Cèpe d\'été',
    latin: 'Boletus aestivalis',
    emoji: '🟤',
    moisDebut: 5,
    moisFin: 9,
    tempMin: 15,
    tempMax: 28,
    besoinPluie: 'élevé',
    altitudeMin: 0,
    altitudeMax: 1000,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['chêne', 'hêtre', 'châtaignier'],
    description: 'Premier cèpe de la saison, chapeau brun clair à surface légèrement craquelée.',
    confusionsDangereuses: 'Bolet satan (Rubroboletus satanas) — toxique. Pied rouge, chair bleuissante.',
    comestibilite: 'excellent',
  },
  {
    id: 'cepe-bronze',
    nom: 'Cèpe bronzé',
    latin: 'Boletus aereus',
    emoji: '⬛',
    moisDebut: 7,
    moisFin: 10,
    tempMin: 16,
    tempMax: 28,
    besoinPluie: 'élevé',
    altitudeMin: 0,
    altitudeMax: 800,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['chêne', 'châtaignier'],
    description: 'Le plus savoureux des cèpes, chapeau brun-noir velouté, typique du sud de la France.',
    confusionsDangereuses: 'Bolet amer (Tylopilus felleus) — non toxique mais immangeable. Réseau brun sur le pied.',
    comestibilite: 'excellent',
  },
  {
    id: 'oronge',
    nom: 'Amanite des Césars',
    latin: 'Amanita caesarea',
    emoji: '🟠',
    moisDebut: 8,
    moisFin: 11,
    tempMin: 18,
    tempMax: 30,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 800,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['chêne', 'châtaignier', 'chêne vert'],
    description: 'Le roi des champignons. Chapeau orange vif, lamelles jaunes, volve blanche.',
    confusionsDangereuses: 'Amanite tue-mouches (Amanita muscaria) — toxique. Chapeau rouge à points blancs, lamelles blanches.',
    comestibilite: 'excellent',
  },
  {
    id: 'rose-des-pres',
    nom: 'Rosé des prés',
    latin: 'Agaricus campestris',
    emoji: '⬜',
    moisDebut: 8,
    moisFin: 11,
    tempMin: 12,
    tempMax: 25,
    besoinPluie: 'élevé',
    altitudeMin: 0,
    altitudeMax: 1000,
    expositionPreferee: 'indifférent',
    pentePreferee: 'plat',
    essences: ['prairie', 'pâturage'],
    description: 'Le champignon de Paris sauvage. Lamelles roses puis brunes, odeur agréable d\'anis.',
    confusionsDangereuses: 'Amanite phalloïde (Amanita phalloides) — mortel ! Lamelles blanches, volve, anneau. TOUJOURS vérifier la couleur des lamelles.',
    comestibilite: 'excellent',
  },

  // ═══════ AUTOMNE ═══════
  {
    id: 'cepe-bordeaux',
    nom: 'Cèpe de Bordeaux',
    latin: 'Boletus edulis',
    emoji: '🟤',
    moisDebut: 8,
    moisFin: 11,
    tempMin: 8,
    tempMax: 18,
    besoinPluie: 'élevé',
    altitudeMin: 0,
    altitudeMax: 2000,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['chêne', 'hêtre', 'châtaignier', 'épicéa'],
    description: 'Le roi des cèpes. Chapeau brun brillant, pied ventru avec réseau blanc, chair ferme.',
    confusionsDangereuses: 'Bolet amer (Tylopilus felleus) — non toxique mais immangeable. Réseau brun sur le pied, pores roses.',
    comestibilite: 'excellent',
  },
  {
    id: 'cepe-pins',
    nom: 'Cèpe des pins',
    latin: 'Boletus pinophilus',
    emoji: '🟤',
    moisDebut: 5,
    moisFin: 11,
    tempMin: 6,
    tempMax: 16,
    besoinPluie: 'élevé',
    altitudeMin: 200,
    altitudeMax: 1800,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['pin sylvestre', 'pin maritime', 'épicéa'],
    description: 'Grand cèpe au chapeau brun-rouge, typique des forêts de conifères.',
    confusionsDangereuses: 'Bolet amer (Tylopilus felleus) — non toxique mais très amer.',
    comestibilite: 'excellent',
  },
  {
    id: 'trompette-mort',
    nom: 'Trompette de la mort',
    latin: 'Craterellus cornucopioides',
    emoji: '⬛',
    moisDebut: 9,
    moisFin: 12,
    tempMin: 6,
    tempMax: 16,
    besoinPluie: 'très élevé',
    altitudeMin: 0,
    altitudeMax: 1500,
    expositionPreferee: 'ombre',
    pentePreferee: 'douce',
    essences: ['hêtre', 'chêne', 'charme'],
    description: 'Champignon noir en forme de trompette, pousse en colonies dans les feuilles mortes.',
    confusionsDangereuses: 'Peu de confusion possible grâce à sa forme caractéristique.',
    comestibilite: 'excellent',
  },
  {
    id: 'pied-mouton',
    nom: 'Pied de mouton',
    latin: 'Hydnum repandum',
    emoji: '⬜',
    moisDebut: 8,
    moisFin: 12,
    tempMin: 5,
    tempMax: 15,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1500,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'indifférent',
    essences: ['hêtre', 'chêne', 'épicéa', 'sapin'],
    description: 'Champignon blanc-crème à aiguillons sous le chapeau (pas de lamelles). Saveur poivrée.',
    confusionsDangereuses: 'Aucune confusion dangereuse. Les aiguillons le rendent facile à identifier.',
    comestibilite: 'bon',
  },
  {
    id: 'coulemelle',
    nom: 'Coulemelle',
    latin: 'Macrolepiota procera',
    emoji: '⬜',
    moisDebut: 8,
    moisFin: 11,
    tempMin: 10,
    tempMax: 22,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1000,
    expositionPreferee: 'indifférent',
    pentePreferee: 'plat',
    essences: ['lisière', 'clairière', 'prairie'],
    description: 'Grande lépiote élégante pouvant atteindre 40cm, anneau mobile sur le pied.',
    confusionsDangereuses: 'Lépiotes toxiques de petite taille (< 12cm). Ne JAMAIS ramasser de petites lépiotes.',
    comestibilite: 'bon',
  },
  {
    id: 'lactaire-delicieux',
    nom: 'Lactaire délicieux',
    latin: 'Lactarius deliciosus',
    emoji: '🟠',
    moisDebut: 9,
    moisFin: 11,
    tempMin: 6,
    tempMax: 16,
    besoinPluie: 'modéré',
    altitudeMin: 200,
    altitudeMax: 1500,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['pin sylvestre', 'pin maritime', 'épicéa'],
    description: 'Champignon orangé sous les pins, lait orange à la cassure qui verdit.',
    confusionsDangereuses: 'Lactaire sanguin (comestible) ou lactaire à lait abondant (sans intérêt). Pas de confusion dangereuse.',
    comestibilite: 'bon',
  },
  {
    id: 'pied-bleu',
    nom: 'Pied-bleu',
    latin: 'Lepista nuda',
    emoji: '🟣',
    moisDebut: 10,
    moisFin: 12,
    tempMin: 4,
    tempMax: 14,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1200,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'indifférent',
    essences: ['hêtre', 'chêne', 'conifère', 'haie'],
    description: 'Champignon tardif violet-lilas caractéristique, parfum anisé.',
    confusionsDangereuses: 'Cortinaires violets (Cortinarius spp.) — certains toxiques mortels. Vérifier l\'absence de cortine (voile).',
    comestibilite: 'bon',
  },
  {
    id: 'clitocybe-geotrope',
    nom: 'Clitocybe géotrope',
    latin: 'Infundibulicybe geotropa',
    emoji: '⬜',
    moisDebut: 10,
    moisFin: 12,
    tempMin: 5,
    tempMax: 15,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1200,
    expositionPreferee: 'indifférent',
    pentePreferee: 'plat',
    essences: ['chêne', 'hêtre', 'lisière', 'clairière'],
    description: 'Grand champignon en entonnoir, pousse en ronds de sorcière en automne.',
    confusionsDangereuses: 'Clitocybe nébuleux (Clitocybe nebularis) — toxique pour certaines personnes. Entolome livide (Entoloma sinuatum) — toxique grave.',
    comestibilite: 'bon',
  },
  {
    id: 'russule-charbonniere',
    nom: 'Russule charbonnière',
    latin: 'Russula cyanoxantha',
    emoji: '🟣',
    moisDebut: 6,
    moisFin: 11,
    tempMin: 10,
    tempMax: 22,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1200,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'indifférent',
    essences: ['chêne', 'hêtre', 'châtaignier'],
    description: 'La meilleure des russules, chapeau violet-vert variable, lamelles souples au toucher.',
    confusionsDangereuses: 'Russules âcres (test au goût). La charbonnière a des lamelles grasses et souples, non cassantes.',
    comestibilite: 'bon',
  },
  {
    id: 'chanterelle-tube',
    nom: 'Chanterelle en tube',
    latin: 'Craterellus tubaeformis',
    emoji: '🟡',
    moisDebut: 9,
    moisFin: 12,
    tempMin: 4,
    tempMax: 14,
    besoinPluie: 'très élevé',
    altitudeMin: 200,
    altitudeMax: 1500,
    expositionPreferee: 'ombre',
    pentePreferee: 'douce',
    essences: ['épicéa', 'sapin', 'hêtre', 'mousse'],
    description: 'Petite chanterelle brun-jaune en forme de tube, pousse en troupes dans la mousse.',
    confusionsDangereuses: 'Peu de confusion possible. Forme caractéristique.',
    comestibilite: 'bon',
  },

  // ═══════ HIVER ═══════
  {
    id: 'pleurote-huitre',
    nom: 'Pleurote en huître',
    latin: 'Pleurotus ostreatus',
    emoji: '⬜',
    moisDebut: 10,
    moisFin: 3,
    tempMin: 0,
    tempMax: 12,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 1000,
    expositionPreferee: 'ombre',
    pentePreferee: 'indifférent',
    essences: ['hêtre', 'peuplier', 'saule', 'orme'],
    description: 'Champignon en forme d\'huître poussant en touffes sur les troncs d\'arbres morts ou affaiblis.',
    confusionsDangereuses: 'Pleurote du panicaut (comestible). Crepidotus (sans intérêt). Pas de confusion dangereuse.',
    comestibilite: 'bon',
  },
  {
    id: 'collybie-pied-veloute',
    nom: 'Collybie à pied velouté',
    latin: 'Flammulina velutipes',
    emoji: '🟡',
    moisDebut: 11,
    moisFin: 3,
    tempMin: -2,
    tempMax: 10,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 800,
    expositionPreferee: 'indifférent',
    pentePreferee: 'indifférent',
    essences: ['saule', 'orme', 'sureau', 'peuplier'],
    description: 'Champignon d\'hiver au chapeau jaune-orangé visqueux, pied velouté brun-noir.',
    confusionsDangereuses: 'Galère marginée (Galerina marginata) — mortel ! Vérifier le pied velouté noir caractéristique.',
    comestibilite: 'bon',
  },
  {
    id: 'truffe-noire',
    nom: 'Truffe noire du Périgord',
    latin: 'Tuber melanosporum',
    emoji: '⬛',
    moisDebut: 12,
    moisFin: 3,
    tempMin: 2,
    tempMax: 12,
    besoinPluie: 'modéré',
    altitudeMin: 100,
    altitudeMax: 800,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'douce',
    essences: ['chêne truffier', 'noisetier', 'chêne vert'],
    description: 'La reine des truffes. Pousse sous terre, nécessite un chien truffier pour la trouver.',
    confusionsDangereuses: 'Autres truffes de moindre qualité (T. brumale, T. indicum). Pas de confusion dangereuse.',
    comestibilite: 'excellent',
  },
  {
    id: 'oreille-judas',
    nom: 'Oreille de Judas',
    latin: 'Auricularia auricula-judae',
    emoji: '🟤',
    moisDebut: 1,
    moisFin: 12,
    tempMin: 0,
    tempMax: 20,
    besoinPluie: 'élevé',
    altitudeMin: 0,
    altitudeMax: 1000,
    expositionPreferee: 'ombre',
    pentePreferee: 'indifférent',
    essences: ['sureau', 'orme', 'hêtre', 'noyer'],
    description: 'Champignon en forme d\'oreille, gélatineux, brun translucide, pousse sur le bois mort.',
    confusionsDangereuses: 'Aucune confusion dangereuse. Forme très caractéristique.',
    comestibilite: 'moyen',
  },

  // ═══════ FIN D'ÉTÉ / AUTOMNE ═══════
  {
    id: 'langue-boeuf',
    nom: 'Langue de bœuf',
    latin: 'Fistulina hepatica',
    emoji: '🔴',
    moisDebut: 8,
    moisFin: 11,
    tempMin: 10,
    tempMax: 22,
    besoinPluie: 'modéré',
    altitudeMin: 0,
    altitudeMax: 800,
    expositionPreferee: 'mi-ombre',
    pentePreferee: 'indifférent',
    essences: ['chêne', 'châtaignier'],
    description: 'Champignon charnu rouge sang en forme de langue, pousse au pied des chênes et châtaigniers.',
    confusionsDangereuses: 'Aucune confusion dangereuse. Forme et couleur uniques.',
    comestibilite: 'moyen',
  },
];

/**
 * Filtre les espèces par mois courant
 */
export function getSpeciesByMonth(month: number): MushroomSpecies[] {
  return SPECIES.filter(s => {
    if (s.moisDebut <= s.moisFin) {
      return month >= s.moisDebut && month <= s.moisFin;
    }
    // Espèces à cheval sur l'année (ex: nov → mars)
    return month >= s.moisDebut || month <= s.moisFin;
  });
}

/**
 * Filtre les espèces par conditions terrain + météo
 */
export function getSpeciesForConditions(
  month: number,
  avgTemp: number,
  altitude: number
): MushroomSpecies[] {
  return getSpeciesByMonth(month).filter(s => {
    const tempOk = avgTemp >= s.tempMin - 3 && avgTemp <= s.tempMax + 3;
    const altOk = altitude >= s.altitudeMin && altitude <= s.altitudeMax;
    return tempOk && altOk;
  });
}

// ═══════ SPOTS PRÉDÉFINIS ═══════

export const SPOTS: Spot[] = [
  { name: 'Forêt de Fontainebleau', lat: 48.40, lon: 2.64, region: 'Île-de-France' },
  { name: 'Forêt de Rambouillet', lat: 48.60, lon: 1.82, region: 'Île-de-France' },
  { name: 'Forêt de Compiègne', lat: 49.38, lon: 2.90, region: 'Hauts-de-France' },
  { name: 'Vosges — Gérardmer', lat: 48.07, lon: 6.88, region: 'Grand Est' },
  { name: 'Dordogne — Périgord', lat: 45.18, lon: 0.72, region: 'Nouvelle-Aquitaine' },
  { name: 'Sologne', lat: 47.50, lon: 1.90, region: 'Centre-Val de Loire' },
  { name: 'Forêt des Landes', lat: 44.00, lon: -0.78, region: 'Nouvelle-Aquitaine' },
  { name: 'Jura — Les Rousses', lat: 46.48, lon: 6.06, region: 'Bourgogne-Franche-Comté' },
  { name: 'Forêt de Tronçais', lat: 46.66, lon: 2.72, region: 'Auvergne' },
  { name: 'Forêt de Brocéliande', lat: 48.07, lon: -2.24, region: 'Bretagne' },
  { name: 'Massif des Maures', lat: 43.40, lon: 6.30, region: 'PACA' },
  { name: 'Cévennes', lat: 44.27, lon: 3.58, region: 'Occitanie' },
];
