// ============================================================
// ChampIndex — Alertes météo déclenchantes
// Généré par scripts/import-habitats.mjs — 20 alertes
// ============================================================

export interface WeatherAlert {
  id: string;
  condition: string;
  targetSpecies: string;
  whereToLook: string;
  period: string;
  reliability: 'high' | 'medium' | 'low';
  appMessage: string;
}

export const WEATHER_ALERTS: WeatherAlert[] = [
  {
    id: 'alert-1',
    condition: 'Pluie > 20mm + T° 15-22°C + 10-15 jours après',
    targetSpecies: 'Cèpes',
    whereToLook: 'Toutes forêts de feuillus',
    period: 'Sep-Nov',
    reliability: 'high',
    appMessage: 'Pic de pousse probable. Vérifier les coins à cèpes.',
  },
  {
    id: 'alert-2',
    condition: 'Pluie continue 3+ jours + T° 8-15°C',
    targetSpecies: 'Trompettes de la mort',
    whereToLook: 'Hêtraies humides',
    period: 'Oct-Nov',
    reliability: 'high',
    appMessage: 'Conditions idéales. Sol détrempé sous hêtres.',
  },
  {
    id: 'alert-3',
    condition: 'Pluie modérée + T° 15-25°C + humidité constante',
    targetSpecies: 'Girolles',
    whereToLook: 'Forêts de feuillus et mixtes',
    period: 'Jun-Oct',
    reliability: 'medium',
    appMessage: 'Pousse lente mais continue si sol reste humide.',
  },
  {
    id: 'alert-4',
    condition: 'T° sol > 10°C + pluie printanière + alternance soleil',
    targetSpecies: 'Morilles',
    whereToLook: 'Frênaies, vergers, sols calcaires',
    period: 'Mar-Mai',
    reliability: 'high',
    appMessage: 'Quand les lilas fleurissent ! Chercher sous les frênes.',
  },
  {
    id: 'alert-5',
    condition: 'T° 12-18°C + sol réchauffé + pluie douce',
    targetSpecies: 'Mousserons de St-Georges',
    whereToLook: 'Prairies, haies, vergers',
    period: 'Avr-Mai',
    reliability: 'medium',
    appMessage: 'Autour du 23 avril traditionnellement.',
  },
  {
    id: 'alert-6',
    condition: 'Nuits fraîches + rosée + pluie puis beau 3-5j',
    targetSpecies: 'Rosés des prés',
    whereToLook: 'Prairies non traitées',
    period: 'Août-Oct',
    reliability: 'medium',
    appMessage: 'Après orages de fin d\'été. Vérifier prairies au petit matin.',
  },
  {
    id: 'alert-7',
    condition: 'Choc thermique (baisse > 10°C) + pluie',
    targetSpecies: 'Pleurotes',
    whereToLook: 'Troncs morts de feuillus',
    period: 'Oct-Mar',
    reliability: 'medium',
    appMessage: 'Le choc thermique déclenche la fructification.',
  },
  {
    id: 'alert-8',
    condition: 'Premières gelées + T° jour > 5°C',
    targetSpecies: 'Pied bleu',
    whereToLook: 'Lisières, haies, feuilles mortes',
    period: 'Nov-Dec',
    reliability: 'low',
    appMessage: 'Un des derniers de la saison.',
  },
  {
    id: 'alert-9',
    condition: 'T° > 15°C + sol humide + fin d\'hiver',
    targetSpecies: 'Ail des ours',
    whereToLook: 'Sous-bois humides, hêtraies',
    period: 'Mar-Avr',
    reliability: 'high',
    appMessage: 'Avant feuillaison des arbres. Disparaît en mai.',
  },
  {
    id: 'alert-10',
    condition: 'Pluie printanière + T° > 10°C',
    targetSpecies: 'Ortie (jeunes pousses)',
    whereToLook: 'Décombres, haies, sols riches',
    period: 'Mar-Mai',
    reliability: 'low',
    appMessage: 'Repousse aussi en automne après coupe.',
  },
  {
    id: 'alert-11',
    condition: 'Grande marée coeff > 90',
    targetSpecies: 'Algues comestibles',
    whereToLook: 'Estran rocheux Bretagne/Normandie',
    period: 'Toute l\'année',
    reliability: 'high',
    appMessage: 'Vérifier horaires de marée. Cueillette à marée basse.',
  },
  {
    id: 'alert-12',
    condition: 'T° > 18°C + été',
    targetSpecies: 'Salicorne',
    whereToLook: 'Marais salants, prés salés',
    period: 'Jun-Sep',
    reliability: 'low',
    appMessage: 'Cueillir les extrémités tendres uniquement.',
  },
  {
    id: 'alert-13',
    condition: 'Été chaud + quelques pluies',
    targetSpecies: 'Mûres',
    whereToLook: 'Haies, lisières',
    period: 'Jul-Sep',
    reliability: 'low',
    appMessage: 'Plus il fait chaud et sec, plus elles sont sucrées.',
  },
  {
    id: 'alert-14',
    condition: 'Premières gelées d\'automne',
    targetSpecies: 'Prunelles, cynorhodons',
    whereToLook: 'Haies',
    period: 'Nov-Dec',
    reliability: 'low',
    appMessage: 'Le gel ramollit la pulpe et réduit l\'astringence.',
  },
  {
    id: 'alert-15',
    condition: 'Été humide de montagne',
    targetSpecies: 'Myrtilles',
    whereToLook: 'Sous-bois acides, landes de montagne',
    period: 'Jul-Août',
    reliability: 'medium',
    appMessage: 'Gelées tardives de printemps = mauvaise récolte.',
  },
  {
    id: 'alert-16',
    condition: 'Pluie d\'été (juil-août) suffisante puis hiver frais',
    targetSpecies: 'Truffe noire',
    whereToLook: 'Chênaie calcaire (Sud)',
    period: 'Dec-Mar',
    reliability: 'high',
    appMessage: 'Été sec = mauvaise saison trufficole.',
  },
  {
    id: 'alert-17',
    condition: 'Bogues ouvertes, premières gelées légères',
    targetSpecies: 'Châtaignes',
    whereToLook: 'Châtaigneraies',
    period: 'Oct-Nov',
    reliability: 'low',
    appMessage: 'Après gelées, les bogues s\'ouvrent naturellement.',
  },
  {
    id: 'alert-18',
    condition: 'Pluie abondante puis 5-7j de beau temps + T° 10-20°C',
    targetSpecies: 'Coulemelle',
    whereToLook: 'Lisières, clairières, prairies',
    period: 'Sep-Nov',
    reliability: 'medium',
    appMessage: 'Avec les premiers brouillards d\'automne.',
  },
  {
    id: 'alert-19',
    condition: 'T° nocturne < 10°C + pluie automnale',
    targetSpecies: 'Chanterelles en tube',
    whereToLook: 'Hêtraies humides, mousses',
    period: 'Oct-Dec',
    reliability: 'medium',
    appMessage: 'Pousse tardive, résiste bien au froid.',
  },
  {
    id: 'alert-20',
    condition: 'Pluie 8-12j avant + T° 15-25°C + altitude > 500m',
    targetSpecies: 'Cèpes de montagne',
    whereToLook: 'Hêtraies-sapinières d\'altitude',
    period: 'Août-Oct',
    reliability: 'high',
    appMessage: 'Saison plus précoce qu\'en plaine (août).',
  },
];
